/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Empsearch;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Employee;

/**
 *
 * @author Gihan
 */
public final class AdvanceUI extends javax.swing.JPanel {

    Empsearch empsearch = new Empsearch();
    Employee emp;
    int updateid;
    int empno = 0;
    int epfno = 0;

    /**
     * Creates new form AdvanceUI
     */
    public AdvanceUI() {
        initComponents();
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        updateTable();
    }
    
    
    public void updateTable(){
    DefaultTableModel df = (DefaultTableModel) tblsal.getModel();
        df.setRowCount(0);
        try {
            ResultSet rs = new Employee().getEmpAdvance(Employee.ALLEMPLOYES, ycyear.getYear(), mcmonth.getMonth() + 1);
            while (rs.next()) {
                ArrayList ar = new ArrayList();
                ar.add(rs.getString("EmpNumber"));
                ar.add(rs.getString("FMName") + " " + rs.getString("LName"));
                ar.add(rs.getString("Advance"));
                ar.add(rs.getString("Date")+" "+rs.getString("Time"));
                ar.add(rs.getString("year"));
                ar.add(rs.getString("month"));
                df.addRow(ar.toArray());
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrollemp = new javax.swing.JScrollPane();
        listemp = new javax.swing.JList();
        lepfnum = new javax.swing.JLabel();
        tename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tadvance = new javax.swing.JTextField();
        lenum = new javax.swing.JLabel();
        bdelete = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ycyear = new com.toedter.calendar.JYearChooser();
        jLabel16 = new javax.swing.JLabel();
        mcmonth = new com.toedter.calendar.JMonthChooser();
        bsave1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsal = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Emp. Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 65, 27));

        listemp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        listemp.setForeground(new java.awt.Color(51, 51, 51));
        listemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listempMouseClicked(evt);
            }
        });
        listemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listempKeyPressed(evt);
            }
        });
        scrollemp.setViewportView(listemp);

        jPanel1.add(scrollemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 250, 30));

        lepfnum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lepfnum.setForeground(new java.awt.Color(51, 51, 51));
        lepfnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lepfnum.setText("EPF. No:");
        lepfnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lepfnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, 27));

        tename.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tename.setForeground(new java.awt.Color(51, 51, 51));
        tename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tenameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenameKeyReleased(evt);
            }
        });
        jPanel1.add(tename, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Advance ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 27));

        tadvance.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tadvance.setForeground(new java.awt.Color(51, 51, 51));
        tadvance.setText("0.0");
        tadvance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tadvanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tadvanceKeyReleased(evt);
            }
        });
        jPanel1.add(tadvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 90, 29));

        lenum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lenum.setForeground(new java.awt.Color(51, 51, 51));
        lenum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lenum.setText("Emp.No:");
        lenum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 27));

        bdelete.setText("Update");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 110, 40));

        bsave.setText("Save Data");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Year");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 38, 27));
        jPanel1.add(ycyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 27));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Month");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 44, 27));

        mcmonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(mcmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 27));

        bsave1.setText("Reload Table");
        bsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsave1ActionPerformed(evt);
            }
        });
        jPanel1.add(bsave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 420, 10));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgtop_advance.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tblsal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tblsal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp.No", "Full Name", "Advance", "Date-Time", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblsal.setRowHeight(21);
        tblsal.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblsal.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblsal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblsalMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblsal);
        tblsal.getColumnModel().getColumn(0).setMinWidth(60);
        tblsal.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblsal.getColumnModel().getColumn(0).setMaxWidth(60);
        tblsal.getColumnModel().getColumn(2).setMinWidth(80);
        tblsal.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblsal.getColumnModel().getColumn(2).setMaxWidth(80);
        tblsal.getColumnModel().getColumn(4).setMinWidth(0);
        tblsal.getColumnModel().getColumn(4).setPreferredWidth(0);
        tblsal.getColumnModel().getColumn(4).setMaxWidth(0);
        tblsal.getColumnModel().getColumn(5).setMinWidth(0);
        tblsal.getColumnModel().getColumn(5).setPreferredWidth(0);
        tblsal.getColumnModel().getColumn(5).setMaxWidth(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listempMouseClicked
        genmethod();
    }//GEN-LAST:event_listempMouseClicked

    private void listempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listempKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            genmethod();
        }
    }//GEN-LAST:event_listempKeyPressed

    private void tenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listemp.grabFocus();

        }
    }//GEN-LAST:event_tenameKeyPressed

    private void tenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenameKeyReleased
        empsearch = new Empsearch();
        empsearch.employeeSearch(listemp, scrollemp, tename.getText());

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listemp.grabFocus();

        }
    }//GEN-LAST:event_tenameKeyReleased

    private void tadvanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tadvanceKeyPressed
    }//GEN-LAST:event_tadvanceKeyPressed

    private void tadvanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tadvanceKeyReleased
    }//GEN-LAST:event_tadvanceKeyReleased

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        if (!tadvance.getText().isEmpty()) {
            
            emp.setAdvance(Double.parseDouble(tadvance.getText()));
            emp.AddvanceUpdate(ycyear.getYear(), mcmonth.getMonth() + 1);
            updateTable();
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        if (!tadvance.getText().isEmpty()) {

            Employee emp1 = new Employee();
            emp1.setEmpno(empno);
            emp1.setAdvance(Double.parseDouble(tadvance.getText()));
            emp1.AddvanceSave(ycyear.getYear(), mcmonth.getMonth() + 1);
             updateTable();
        }

    }//GEN-LAST:event_bsaveActionPerformed

    private void tblsalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsalMouseClicked
        if (tblsal.getSelectedRow() != -1) {
            bsave.setEnabled(false);
            int empno1 = Integer.parseInt(tblsal.getValueAt(tblsal.getSelectedRow(), 0).toString());
            String year = tblsal.getValueAt(tblsal.getSelectedRow(), 4).toString();
            String month = tblsal.getValueAt(tblsal.getSelectedRow(), 5).toString();
            emp = new Employee();
            
            emp.setEmpno(empno1);
            emp.setAdvanceTaknYear(Integer.parseInt(year));
            emp.setAvannceTakinMonth(Integer.parseInt(month));
            ResultSet rs = emp.getEmpAdvance(Employee.THISEMPLOYE, ycyear.getYear(), mcmonth.getMonth() + 1);
            try {
                if (rs.next()) {
                    tename.setText(rs.getString("FMName") + " " + rs.getString("LName") + "-" + rs.getString("EmpNumber"));
                    tadvance.setText(rs.getString("Advance"));
                    ycyear.setYear(rs.getInt("year"));
                    mcmonth.setMonth(rs.getInt("month") - 1);
                    lenum.setText("Emp.No: " + empno1);
                    lepfnum.setText("EPF. No: " + rs.getString("EpFNumber"));

                }

            } catch (Exception e) {
                System.out.println("error in table click" + e);
            }
        }
    }//GEN-LAST:event_tblsalMouseClicked

    private void bsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsave1ActionPerformed
        updateTable();
        
        
    }//GEN-LAST:event_bsave1ActionPerformed

    private void tblsalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblsalMouseEntered

    public void genmethod() {

        empsearch = new Empsearch();
        tename.setText("" + listemp.getSelectedValue());
        scrollemp.setSize(scrollemp.getWidth(), 0);
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        tadvance.grabFocus();

        this.empno = empsearch.getEmployeeNumber(tename.getText());

        lenum.setText("Emp.No: " + empno);
        lepfnum.setText("EPF. No: " + new Employee(epfno).getEPFNumber());



    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bsave1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lenum;
    private javax.swing.JLabel lepfnum;
    private javax.swing.JList listemp;
    private com.toedter.calendar.JMonthChooser mcmonth;
    private javax.swing.JScrollPane scrollemp;
    private javax.swing.JTextField tadvance;
    private javax.swing.JTable tblsal;
    private javax.swing.JTextField tename;
    private com.toedter.calendar.JYearChooser ycyear;
    // End of variables declaration//GEN-END:variables
}
