/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.OftnLogic;

/**
 *
 * @author Gihan
 */
public class AllemployeeUI extends javax.swing.JPanel {

    /**
     * Creates new form AllemployeeUI
     */
    public AllemployeeUI() {
        initComponents();
        load();
        TotalEmployess.setText("Total Employe Count :- " + allemployees.getRowCount());
    }

    public void load() {
        if (activein.getSelectedIndex() == 2) {
            int count = 0;
            ResultSet rs = Employee.getOneYearCompletedEmployees(getThisDate());
            DefaultTableModel dt = (DefaultTableModel) allemployees.getModel();
            dt.setRowCount(0);
            try {
                while (rs.next()) {
                    count++;
                    ArrayList vec = new ArrayList();
                    vec.add(rs.getInt("EmpNumber"));
                    vec.add(rs.getInt("EpfNumber"));
                    vec.add(rs.getString("FMname") + " " + rs.getString("Lname"));
                    vec.add(rs.getString("Designation"));
                    vec.add(rs.getString("Site_location"));
                    vec.add(rs.getString("Add_nub") + " " + rs.getString("City"));
                    vec.add(rs.getString("contactMobile"));
                    dt.addRow(vec.toArray());
                }
                ltot.setText(""+count);
            } catch (Exception e) {
                System.out.println("Error From loadTable Method1: " + e);
            }
            
            
        } else {
            int count = 0;
            int active = 0;
            if (activein.getSelectedItem().toString().equals("Active")) {
                active = 1;
            }

            ResultSet rs = Employee.getEmployees(active);
            DefaultTableModel dt = (DefaultTableModel) allemployees.getModel();
            dt.setRowCount(0);
            try {
                while (rs.next()) {
                    count++;
                    ArrayList vec = new ArrayList();
                    vec.add(rs.getInt("EmpNumber"));
                    vec.add(rs.getInt("EpfNumber"));
                    vec.add(rs.getString("FMname") + " " + rs.getString("Lname"));
                    vec.add(rs.getString("Designation"));
                    vec.add(rs.getString("Site_location"));
                    vec.add(rs.getString("Add_nub") + " " + rs.getString("City"));
                    vec.add(rs.getString("contactMobile"));
                    dt.addRow(vec.toArray());
                }
                ltot.setText(""+count);
            } catch (Exception e) {
                System.out.println("Error From loadTable Method2: " + e);
            }
        }

    }
    
    public String getThisDate(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date d = new Date();
        int yr = cal.get(Calendar.YEAR) - 1;
        String curent = yr+""+df.format(d).substring(4, "yyyy-MM-dd".length());
        
        System.out.println(curent);

        return curent;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalEmployess = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allemployees = new javax.swing.JTable();
        activein = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        ltot = new javax.swing.JLabel();

        TotalEmployess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalEmployess.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        setOpaque(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        allemployees.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        allemployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp.No", "EPF No", "Full Name", "Designation", "Site", "Address", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allemployees.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        allemployees.setAutoscrolls(false);
        allemployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        allemployees.setRowHeight(21);
        allemployees.setSelectionBackground(new java.awt.Color(0, 102, 255));
        allemployees.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(allemployees);
        allemployees.getColumnModel().getColumn(0).setMinWidth(80);
        allemployees.getColumnModel().getColumn(0).setPreferredWidth(80);
        allemployees.getColumnModel().getColumn(0).setMaxWidth(80);
        allemployees.getColumnModel().getColumn(1).setMinWidth(80);
        allemployees.getColumnModel().getColumn(1).setPreferredWidth(80);
        allemployees.getColumnModel().getColumn(1).setMaxWidth(80);
        allemployees.getColumnModel().getColumn(2).setMinWidth(250);
        allemployees.getColumnModel().getColumn(2).setPreferredWidth(250);
        allemployees.getColumnModel().getColumn(2).setMaxWidth(250);
        allemployees.getColumnModel().getColumn(3).setMinWidth(200);
        allemployees.getColumnModel().getColumn(3).setPreferredWidth(200);
        allemployees.getColumnModel().getColumn(3).setMaxWidth(200);
        allemployees.getColumnModel().getColumn(4).setMinWidth(150);
        allemployees.getColumnModel().getColumn(4).setPreferredWidth(150);
        allemployees.getColumnModel().getColumn(4).setMaxWidth(150);
        allemployees.getColumnModel().getColumn(5).setPreferredWidth(250);
        allemployees.getColumnModel().getColumn(6).setPreferredWidth(100);

        activein.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive", "One Year Completed" }));
        activein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeinActionPerformed(evt);
            }
        });

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(128, 128, 128));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgtop_list.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jButton3.setText("To Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setText("Total in Table:");

        ltot.setBackground(new java.awt.Color(51, 51, 51));
        ltot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltot.setForeground(new java.awt.Color(102, 0, 0));
        ltot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activein, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltot, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1222, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ltot, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(activein, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(261, 261, 261)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(266, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        load();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void activeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeinActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new OftnLogic().fillData(allemployees);
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalEmployess;
    private javax.swing.JComboBox activein;
    private javax.swing.JTable allemployees;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ltot;
    // End of variables declaration//GEN-END:variables
}
