/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.CalculateSalary;
import control.Empsearch;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.PayRoll;

/**
 *
 * @author Gihan
 */
public class CreatesalaryUI extends javax.swing.JPanel {

    Empsearch empsearch = new Empsearch();
    Employee employee;
    CalculateSalary calsalary;
    public static int Month = -1;

    /**
     * Creates new form CreatesalaryUI
     */
    public CreatesalaryUI() {
        initComponents();
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        if (CreatesalaryUI.Month != -1) {
            mcmonth.setMonth(CreatesalaryUI.Month);
        }


    }

    public void AddRemoveAllownse() {
        lalltot.setText(calsalary.getGrossTotalAlwonse() + "");
        lnprate2.setText(calsalary.calNopayRateForAllownse() + "");
        if (!tnpdays2.getText().trim().isEmpty()) {
            lnptotal2.setText(calsalary.NopayValueForAllwonses() + "");
            lallfinal.setText(calsalary.NetTotalAllownse() + "");
        }
    }

    public void calTotalAdditions() {
        if (calsalary != null) {
            ltotearnings.setText(calsalary.calGrossSalary() + "");
            payee.setText(calsalary.calPAYE() + "");

        }
    }

    public void calFinalTotal() {
        if (calsalary != null) {
            lfinalsalary.setText(calsalary.calFinalSalary() + "");
        }
    }

    public void setTotalDiductions() {
        if (calsalary != null) {
            ltotdeductions.setText(calsalary.calAllTotalDiductions() + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lepfno = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scrollemp = new javax.swing.JScrollPane();
        listemp = new javax.swing.JList();
        tnpdays1 = new javax.swing.JTextField();
        lbsalary = new javax.swing.JLabel();
        tename = new javax.swing.JTextField();
        bremove1 = new javax.swing.JButton();
        badd1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ycyear = new com.toedter.calendar.JYearChooser();
        jLabel16 = new javax.swing.JLabel();
        mcmonth = new com.toedter.calendar.JMonthChooser();
        lempno = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lga = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lba = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lnptotal1 = new javax.swing.JLabel();
        tallowance = new javax.swing.JTextField();
        lnprate1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ladditioncost = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lnprate2 = new javax.swing.JLabel();
        tnpdays2 = new javax.swing.JTextField();
        lnptotal2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lallfinal = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        taddqty = new javax.swing.JTextField();
        badd2 = new javax.swing.JButton();
        bremove2 = new javax.swing.JButton();
        taddamount = new javax.swing.JTextField();
        lalltot = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        laddtotal = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lotrate = new javax.swing.JLabel();
        lothrs = new javax.swing.JTextField();
        lotamount = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        badd3 = new javax.swing.JButton();
        bremove3 = new javax.swing.JButton();
        ldedamount = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        ldedtot = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ltype = new javax.swing.JLabel();
        cmballowance = new com.imal.practicalJcombSearchable.JComboPractical();
        cmbadditional = new com.imal.practicalJcombSearchable.JComboPractical();
        cmbdeduction = new com.imal.practicalJcombSearchable.JComboPractical();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lmsgmain = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblearnings = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldeductions = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ltotearnings = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ltotdeductions = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        payee = new javax.swing.JLabel();
        diductions = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        advance = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lfinalsalary = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        lsalepf = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lepfemployee = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lepfcompany = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        letf = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbalbasic = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        bclear1 = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Emp. Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 65, 27));

        lepfno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lepfno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lepfno.setText("EPF. No:");
        lepfno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lepfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, 27));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("F.Allowances");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 27));

        listemp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        listemp.setForeground(new java.awt.Color(255, 0, 51));
        listemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listempMouseClicked(evt);
            }
        });
        listemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listempKeyPressed(evt);
            }
        });
        scrollemp.setViewportView(listemp);

        jPanel1.add(scrollemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, 30));

        tnpdays1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tnpdays1.setForeground(new java.awt.Color(0, 153, 255));
        tnpdays1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnpdays1KeyReleased(evt);
            }
        });
        jPanel1.add(tnpdays1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 50, 30));

        lbsalary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbsalary.setForeground(new java.awt.Color(0, 0, 255));
        lbsalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbsalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lbsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 27));

        tename.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tename.setForeground(new java.awt.Color(255, 0, 51));
        tename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenameKeyReleased(evt);
            }
        });
        jPanel1.add(tename, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 240, 40));

        bremove1.setText("Rem-");
        bremove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove1ActionPerformed(evt);
            }
        });
        jPanel1.add(bremove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 60, 30));

        badd1.setText("Add+");
        badd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd1ActionPerformed(evt);
            }
        });
        jPanel1.add(badd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Year");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 38, 27));
        jPanel1.add(ycyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 27));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Month");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 10, 40, 27));

        mcmonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcmonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcmonthMouseClicked(evt);
            }
        });
        mcmonth.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mcmonthPropertyChange(evt);
            }
        });
        jPanel1.add(mcmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 27));

        lempno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lempno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lempno.setText("Emp.No:");
        lempno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 27));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("B.Salary:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 27));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Gvt. All:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, 27));

        lga.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lga.setForeground(new java.awt.Color(0, 0, 255));
        lga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lga.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 80, 27));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Bud. All: ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 50, 27));

        lba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lba.setForeground(new java.awt.Color(0, 0, 255));
        lba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lba.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lba, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 80, 27));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("NP. Rate:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 27));

        lnptotal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnptotal1.setForeground(new java.awt.Color(255, 0, 51));
        lnptotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnptotal1.setText("0.00");
        lnptotal1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lnptotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, 30));

        tallowance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tallowance.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(tallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 30));

        lnprate1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnprate1.setForeground(new java.awt.Color(0, 0, 255));
        lnprate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnprate1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lnprate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("All. Total:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 27));

        ladditioncost.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ladditioncost.setForeground(new java.awt.Color(0, 0, 255));
        ladditioncost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ladditioncost.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(ladditioncost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 70, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("NP.Rate:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 60, 27));

        lnprate2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnprate2.setForeground(new java.awt.Color(0, 0, 255));
        lnprate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnprate2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lnprate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 27));

        tnpdays2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tnpdays2.setForeground(new java.awt.Color(0, 153, 255));
        tnpdays2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnpdays2KeyReleased(evt);
            }
        });
        jPanel1.add(tnpdays2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 40, 30));

        lnptotal2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnptotal2.setForeground(new java.awt.Color(0, 0, 255));
        lnptotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnptotal2.setText("0.00");
        lnptotal2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lnptotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 70, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Allowance Final Total:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 27));

        lallfinal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lallfinal.setForeground(new java.awt.Color(0, 102, 0));
        lallfinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lallfinal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        lallfinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lallfinalPropertyChange(evt);
            }
        });
        jPanel1.add(lallfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, 27));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Additionals");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 27));

        taddqty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        taddqty.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(taddqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 70, 30));

        badd2.setText("Add+");
        badd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd2ActionPerformed(evt);
            }
        });
        jPanel1.add(badd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 60, 30));

        bremove2.setText("Rem-");
        bremove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove2ActionPerformed(evt);
            }
        });
        jPanel1.add(bremove2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 60, 30));

        taddamount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        taddamount.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(taddamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 70, 30));

        lalltot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lalltot.setForeground(new java.awt.Color(0, 0, 255));
        lalltot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalltot.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lalltot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 27));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Additional Total:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 130, 27));

        laddtotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        laddtotal.setForeground(new java.awt.Color(0, 102, 0));
        laddtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laddtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        laddtotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                laddtotalPropertyChange(evt);
            }
        });
        jPanel1.add(laddtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 80, 27));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("O.T. Rate:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 60, 27));

        lotrate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lotrate.setForeground(new java.awt.Color(0, 0, 255));
        lotrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotrate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lotrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 70, 30));

        lothrs.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lothrs.setForeground(new java.awt.Color(0, 153, 255));
        lothrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lothrsKeyReleased(evt);
            }
        });
        jPanel1.add(lothrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 70, 30));

        lotamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lotamount.setForeground(new java.awt.Color(0, 0, 255));
        lotamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotamount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lotamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 70, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Deductions");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, 27));

        badd3.setText("Add+");
        badd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd3ActionPerformed(evt);
            }
        });
        jPanel1.add(badd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 60, 30));

        bremove3.setText("Rem-");
        bremove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove3ActionPerformed(evt);
            }
        });
        jPanel1.add(bremove3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 60, 30));

        ldedamount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ldedamount.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(ldedamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 70, 30));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Deduction Total:");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 100, 27));

        ldedtot.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ldedtot.setForeground(new java.awt.Color(255, 0, 51));
        ldedtot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldedtot.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        ldedtot.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ldedtotPropertyChange(evt);
            }
        });
        jPanel1.add(ldedtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 100, 27));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Type:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 50, 27));

        ltype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltype.setForeground(new java.awt.Color(0, 0, 255));
        ltype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltype.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(ltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 80, 27));

        cmballowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmballowanceActionPerformed(evt);
            }
        });
        jPanel1.add(cmballowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        cmbadditional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbadditionalActionPerformed(evt);
            }
        });
        jPanel1.add(cmbadditional, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 150, 30));

        cmbdeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdeductionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbdeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 150, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 420, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 420, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 420, 10));

        lmsgmain.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lmsgmain.setForeground(new java.awt.Color(204, 0, 0));
        lmsgmain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmsgmain.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(lmsgmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 30));

        tblearnings.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tblearnings.setForeground(new java.awt.Color(0, 102, 255));
        tblearnings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Earning", "Amount", "asd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblearnings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblearnings.setRowHeight(21);
        tblearnings.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tblearnings.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane2.setViewportView(tblearnings);
        tblearnings.getColumnModel().getColumn(0).setMinWidth(50);
        tblearnings.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblearnings.getColumnModel().getColumn(0).setMaxWidth(50);
        tblearnings.getColumnModel().getColumn(2).setMinWidth(80);
        tblearnings.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblearnings.getColumnModel().getColumn(2).setMaxWidth(80);
        tblearnings.getColumnModel().getColumn(3).setMinWidth(0);
        tblearnings.getColumnModel().getColumn(3).setPreferredWidth(0);
        tblearnings.getColumnModel().getColumn(3).setMaxWidth(0);

        tbldeductions.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbldeductions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Deductions", "Amount", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldeductions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldeductions.setRowHeight(21);
        tbldeductions.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tbldeductions.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane3.setViewportView(tbldeductions);
        tbldeductions.getColumnModel().getColumn(0).setMinWidth(50);
        tbldeductions.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbldeductions.getColumnModel().getColumn(0).setMaxWidth(50);
        tbldeductions.getColumnModel().getColumn(2).setMinWidth(80);
        tbldeductions.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbldeductions.getColumnModel().getColumn(2).setMaxWidth(80);
        tbldeductions.getColumnModel().getColumn(3).setMinWidth(0);
        tbldeductions.getColumnModel().getColumn(3).setPreferredWidth(0);
        tbldeductions.getColumnModel().getColumn(3).setMaxWidth(0);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Earnings");

        ltotearnings.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ltotearnings.setForeground(new java.awt.Color(0, 102, 0));
        ltotearnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotearnings.setText("0.00");
        ltotearnings.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ltotearningsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ltotearnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ltotearnings, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TO BE DEDUCT");

        ltotdeductions.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ltotdeductions.setForeground(new java.awt.Color(255, 0, 51));
        ltotdeductions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotdeductions.setText("0.00");
        ltotdeductions.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ltotdeductionsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(ltotdeductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(ltotdeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PAYE value");

        payee.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        payee.setForeground(new java.awt.Color(255, 0, 51));
        payee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payee.setText("0.00");
        payee.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                payeePropertyChange(evt);
            }
        });

        diductions.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        diductions.setForeground(new java.awt.Color(255, 0, 51));
        diductions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diductions.setText("0.00");
        diductions.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                diductionsPropertyChange(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Diductions");

        advance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        advance.setForeground(new java.awt.Color(255, 0, 51));
        advance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        advance.setText("0.00");
        advance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                advancePropertyChange(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Advance Taken");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diductions, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advance, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AVAILABLE SALARY");

        lfinalsalary.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lfinalsalary.setForeground(new java.awt.Color(0, 51, 255));
        lfinalsalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lfinalsalary.setText("0.0");
        lfinalsalary.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lfinalsalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lfinalsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(237, 237, 237));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Salary for PF");

        lsalepf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lsalepf.setForeground(new java.awt.Color(0, 0, 255));
        lsalepf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsalepf.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("EPF Employee");

        lepfemployee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lepfemployee.setForeground(new java.awt.Color(255, 0, 51));
        lepfemployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lepfemployee.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("EPF Company");

        lepfcompany.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lepfcompany.setForeground(new java.awt.Color(0, 0, 255));
        lepfcompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lepfcompany.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("ETF");

        letf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        letf.setForeground(new java.awt.Color(0, 0, 255));
        letf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letf.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("B.Basic");

        lbalbasic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbalbasic.setForeground(new java.awt.Color(0, 102, 0));
        lbalbasic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbalbasic.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        lbalbasic.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbalbasicPropertyChange(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(":-");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText(":-");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(":-");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText(":-");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText(":-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lepfcompany, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(lsalepf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbalbasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(letf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lepfemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsalepf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lepfemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lepfcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbalbasic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(128, 128, 128));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgtop_payroll.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        bsave.setText("Save Salary");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        bclear1.setText("Cal Salary");
        bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(bsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1077, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(10, 10, 10))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenameKeyReleased

        empsearch.employeeSearch(listemp, scrollemp, tename.getText());
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listemp.grabFocus();
        }

    }//GEN-LAST:event_tenameKeyReleased

    private void listempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listempKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            showAllData();
        }
    }//GEN-LAST:event_listempKeyPressed

    private void listempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listempMouseClicked
        showAllData();
    }//GEN-LAST:event_listempMouseClicked

    private void badd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd1ActionPerformed
        if (!tallowance.getText().trim().isEmpty()) {
            DefaultTableModel dt = (DefaultTableModel) tblearnings.getModel();
            details d = (details) cmballowance.getSelectedItem();
            String st[] = {"Alow", d.textval, tallowance.getText(), d.ID + ""};
            dt.addRow(st);
            calsalary.UpdateGrossTotalAlwonse(Double.parseDouble(tallowance.getText()));
            AddRemoveAllownse();
        }
    }//GEN-LAST:event_badd1ActionPerformed

    private void tnpdays1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnpdays1KeyReleased
        if (!tnpdays1.getText().trim().isEmpty()) {
            double absnt = Double.parseDouble(tnpdays1.getText());
            calsalary.setAbsentDays(absnt);
            tnpdays2.setText(absnt + "");
            lnptotal1.setText(calsalary.calNopay() + "");
            lsalepf.setText(calsalary.CalSalaryPF() + "");
            lepfemployee.setText(calsalary.calEPFemployee() + "");
            lepfcompany.setText(calsalary.calEPFcompany() + "");
            letf.setText(calsalary.calETF() + "");
            lbalbasic.setText(calsalary.CalBalanceBasic() + "");
            tnpdays2KeyReleased(null);
        }

    }//GEN-LAST:event_tnpdays1KeyReleased

    private void bremove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove1ActionPerformed
        if (tblearnings.getSelectedRow() != -1) {
            int i = tblearnings.getSelectedRow();
            if (tblearnings.getValueAt(i, 0).toString().equals("Alow")) {
                DefaultTableModel dt = (DefaultTableModel) tblearnings.getModel();
                double value = -Double.parseDouble(tblearnings.getValueAt(i, 2).toString());
                calsalary.UpdateGrossTotalAlwonse(value);
                dt.removeRow(i);
                AddRemoveAllownse();
            }
        }
    }//GEN-LAST:event_bremove1ActionPerformed

    private void tnpdays2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnpdays2KeyReleased
        if (!tnpdays2.getText().trim().isEmpty()) {
            lnptotal2.setText(calsalary.NopayValueForAllwonses() + "");
            lallfinal.setText(calsalary.NetTotalAllownse() + "");
        }

    }//GEN-LAST:event_tnpdays2KeyReleased

    private void cmbadditionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbadditionalActionPerformed
        details d = (details) cmbadditional.getSelectedItem();
        taddamount.setText(d.value + "");
    }//GEN-LAST:event_cmbadditionalActionPerformed

    private void badd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd2ActionPerformed
        if (!taddamount.getText().trim().isEmpty() && !taddqty.getText().trim().isEmpty()) {
            DecimalFormat format = new DecimalFormat("#.##");
            DefaultTableModel dt = (DefaultTableModel) tblearnings.getModel();
            String value = format.format(Math.round(Double.parseDouble(taddamount.getText()) * Double.parseDouble(taddqty.getText()))) + "";
            details d = (details) cmbadditional.getSelectedItem();
            String st[] = {"ADD", d.textval + " - " + taddamount.getText() + " X " + taddqty.getText(), value, d.ID + ""};
            dt.addRow(st);
            double thisadtin = Double.parseDouble(taddamount.getText()) * Double.parseDouble(taddqty.getText());
            calsalary.UpadateAdditions(thisadtin);
            ladditioncost.setText(calsalary.getGrossTotalAddition() + "");
            lothrsKeyReleased(null);
        }
    }//GEN-LAST:event_badd2ActionPerformed

    private void cmballowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmballowanceActionPerformed
        details d = (details) cmballowance.getSelectedItem();
        tallowance.setText(d.value + "");
    }//GEN-LAST:event_cmballowanceActionPerformed

    private void badd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd3ActionPerformed
        if (!ldedamount.getText().trim().isEmpty()) {
            DefaultTableModel dt = (DefaultTableModel) tbldeductions.getModel();
            details dd = (details) cmbdeduction.getSelectedItem();
            String st[] = {"DID", dd.textval, ldedamount.getText(), dd.ID + ""};
            dt.addRow(st);

            calsalary.UpdateTotalDiductions(Double.parseDouble(ldedamount.getText()));
            ldedtot.setText(calsalary.getTotalDiductions() + "");
            diductions.setText(calsalary.getTotalDiductions() + "");
        }
    }//GEN-LAST:event_badd3ActionPerformed

    private void bremove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove3ActionPerformed
        if (tbldeductions.getSelectedRow() != -1) {
            int i = tbldeductions.getSelectedRow();
            if (tbldeductions.getValueAt(i, 0).toString().equals("DID")) {
                DefaultTableModel dt = (DefaultTableModel) tbldeductions.getModel();
                double diduction = -Double.parseDouble(tbldeductions.getValueAt(i, 2).toString());
                dt.removeRow(i);
                calsalary.UpdateTotalDiductions(diduction);
                ldedtot.setText(calsalary.getTotalDiductions() + "");
                diductions.setText(calsalary.getTotalDiductions() + "");
            }
        }
    }//GEN-LAST:event_bremove3ActionPerformed

    private void bremove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove2ActionPerformed
        if (tblearnings.getSelectedRow() != -1) {
            int i = tblearnings.getSelectedRow();
            if (tblearnings.getValueAt(i, 0).toString().equals("ADD")) {
                DefaultTableModel dt = (DefaultTableModel) tblearnings.getModel();
                double rmoveval = -Double.parseDouble(tblearnings.getValueAt(i, 2).toString());
                dt.removeRow(i);
                calsalary.UpadateAdditions(rmoveval);
                ladditioncost.setText(calsalary.getGrossTotalAddition() + "");
                lothrsKeyReleased(null);
            }
        }
    }//GEN-LAST:event_bremove2ActionPerformed

    private void lothrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lothrsKeyReleased
        double othours = 0;
        if (!lothrs.getText().trim().isEmpty()) {
            othours = Double.parseDouble(lothrs.getText());
        }
        calsalary.setOThours(othours);
        lotamount.setText(calsalary.callOT() + "");
        laddtotal.setText(calsalary.calTotalAdditions() + "");
    }//GEN-LAST:event_lothrsKeyReleased

    private void bclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear1ActionPerformed
        calFinalTotal();

    }//GEN-LAST:event_bclear1ActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        if (employee != null) {
            calFinalTotal();

            if (employee.getMsg().equals("Duplicate")) {
                if (calsalary != null) {
                    PayRoll payrl = new PayRoll(calsalary);
                    payrl.setAlloAddValues(tblearnings);
                    payrl.setDeductions(tbldeductions);

                    if (payrl.updatePayroll(employee.getPayrollnumber())) {
                        JOptionPane.showMessageDialog(null, "Salary Details has been successfully Updated", "DONE!", JOptionPane.INFORMATION_MESSAGE);
                        calsalary = null;
                        employee = null;
                        MainUI1.ui.pageSwitch(new CreatesalaryUI());
                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry, Unexpected error occured, Try again!! if this problems continues please Contact Dean Technologies", "UNEXPECTED ERROR", JOptionPane.WARNING_MESSAGE);
                    }

                }
            } else {
                if (calsalary != null) {
                    PayRoll payrl = new PayRoll(calsalary);
                    payrl.setAlloAddValues(tblearnings);
                    payrl.setDeductions(tbldeductions);

                    if (payrl.AddRecordToDb()) {
                        JOptionPane.showMessageDialog(null, "Salary Details has been successfully added", "DONE!", JOptionPane.INFORMATION_MESSAGE);
                        calsalary = null;
                        employee = null;
                        MainUI1.ui.pageSwitch(new CreatesalaryUI());
                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry, Unexpected error occured, Try again!! if this problems continues please Contact Dean Technologies", "UNEXPECTED ERROR", JOptionPane.WARNING_MESSAGE);
                    }

                }

            }

            employee = null;
        } else {
            JOptionPane.showMessageDialog(null, "Please Select an employee First", "Error emp selection", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bsaveActionPerformed

    private void ldedtotPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ldedtotPropertyChange
    }//GEN-LAST:event_ldedtotPropertyChange

    private void lbalbasicPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbalbasicPropertyChange
        calTotalAdditions();
    }//GEN-LAST:event_lbalbasicPropertyChange

    private void lallfinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lallfinalPropertyChange
        calTotalAdditions();
    }//GEN-LAST:event_lallfinalPropertyChange

    private void laddtotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_laddtotalPropertyChange
        calTotalAdditions();
    }//GEN-LAST:event_laddtotalPropertyChange

    private void ltotearningsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ltotearningsPropertyChange
        calFinalTotal();
    }//GEN-LAST:event_ltotearningsPropertyChange

    private void payeePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_payeePropertyChange
        setTotalDiductions();
        calFinalTotal();
    }//GEN-LAST:event_payeePropertyChange

    private void diductionsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_diductionsPropertyChange
        setTotalDiductions();
        calFinalTotal();
    }//GEN-LAST:event_diductionsPropertyChange

    private void advancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_advancePropertyChange
        setTotalDiductions();
        calFinalTotal();
    }//GEN-LAST:event_advancePropertyChange

    private void ltotdeductionsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ltotdeductionsPropertyChange
        calFinalTotal();
    }//GEN-LAST:event_ltotdeductionsPropertyChange

    private void cmbdeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdeductionActionPerformed
        details d = (details) cmbdeduction.getSelectedItem();
        ldedamount.setText(d.value + "");
    }//GEN-LAST:event_cmbdeductionActionPerformed

    private void mcmonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcmonthMouseClicked
     
        
    }//GEN-LAST:event_mcmonthMouseClicked

    private void mcmonthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mcmonthPropertyChange
      CreatesalaryUI.Month = mcmonth.getMonth();
    }//GEN-LAST:event_mcmonthPropertyChange

    void showAllData() {
        calsalary = null;
        employee = null;

        tename.setText("" + listemp.getSelectedValue());
        scrollemp.setSize(scrollemp.getWidth(), 0);
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        tnpdays1.grabFocus();

        //employee = new Employee(empsearch.getEmployeeNumber(tename.getText()));
        employee = new Employee(empsearch.getEmployeeNumber(tename.getText()), ycyear.getYear(), mcmonth.getMonth() + 1);
        employee.setAdvanceTaknYear(ycyear.getYear());
        employee.setAvannceTakinMonth(mcmonth.getMonth() + 1);
        calsalary = new CalculateSalary(employee);

        lmsgmain.setText("" + employee.getMsg());
        lempno.setText("Emp.No: " + employee.getEmpno());
        lepfno.setText("EPF. No: " + employee.getEPFNumber());
        lbsalary.setText("" + employee.getBasicSalary());
        lga.setText("" + employee.getGallowance());
        lba.setText("" + employee.getBallowance());
        ltype.setText(employee.getEmployeeTypeName());
        advance.setText(employee.getAdvanceTaken() + "");

        lnprate1.setText("" + calsalary.calNopayRateForBasic());
        lotrate.setText("" + calsalary.calOTrate());
        lalltot.setText(calsalary.getNetTotalAllowance() + "");

        tnpdays1.setText("" + employee.getNpdays());
        tnpdays2.setText("" + employee.getNpdays());
        lothrs.setText("" + employee.getOthours());

//Calculate NoPay & OT Rates........................................................        
        tnpdays1KeyReleased(null);
        lothrsKeyReleased(null);

        try {

            ResultSet rs = null;
            rs = Employee.getAllDiductions(employee.getEmpno());

            while (rs.next()) {
                details d = new details();
                d.ID = rs.getInt("emp_has_extra.extraval_id");
                d.textval = rs.getString("Name");
                d.value = rs.getDouble("Value");
                cmbdeduction.addItem(d);
            }

            rs = Employee.getAllAllownace(employee.getEmpno());
            int countr = 0;
            while (rs.next()) {

                details d = new details();
                d.ID = rs.getInt("emp_has_extra.extraval_id");
                d.textval = rs.getString("Name");
                d.value = rs.getDouble("Value");
                cmballowance.addItem(d);

                cmballowance.setSelectedIndex(countr++);
                badd1ActionPerformed(null);

            }

            rs = Employee.getAdditions(employee.getEmpno());

            while (rs.next()) {
                details d = new details();

                d.textval = rs.getString("addition_name");
                d.value = rs.getDouble("Value");
                d.ID = rs.getInt("emp_has_addition.addition_id");
                cmbadditional.addItem(d);
            }


        } catch (Exception e) {
            System.out.println("Error in add and did loading" + e);
        }

//Load Additional Data from payroll table, when duplicate entry, not for first time................        
        if (employee.getMsg().equals("Duplicate")) {
            DefaultTableModel dt = (DefaultTableModel) tblearnings.getModel();
            DefaultTableModel dt2 = (DefaultTableModel) tbldeductions.getModel();
            double thisadtin = 0.0;
            double thisdeduct = 0.0;

            try {
                ResultSet rsadditions = employee.getPayAdditions();
                while (rsadditions.next()) {
                    int thisadd_id = rsadditions.getInt("addid");
                    String thisadd_text = rsadditions.getString("addtext");
                    double thisadd_price = rsadditions.getDouble("addprice");
                    double thisadd_qty = rsadditions.getDouble("addqty");
                    double thisadd_amount = rsadditions.getDouble("addamount");

                    String st[] = {"ADD", thisadd_text + " - " + thisadd_price + " X " + thisadd_qty, "" + thisadd_amount, thisadd_id + ""};
                    dt.addRow(st);
                    thisadtin += thisadd_amount;

                }

                calsalary.UpadateAdditions(thisadtin);
                ladditioncost.setText(calsalary.getGrossTotalAddition() + "");
                lothrsKeyReleased(null);


            } catch (Exception e) {
                System.out.println("Error: " + e);
                e.printStackTrace();
            }

//Load Deduction Data from payroll table, when duplicate entry, not for first time.........................

            try {
                ResultSet rsdeducts = employee.getPayDeductions();
                while (rsdeducts.next()) {
                    int thisdeduct_id = rsdeducts.getInt("deductid");
                    String thisdeduct_text = rsdeducts.getString("deductname");
                    double thisdeduct_price = rsdeducts.getDouble("deductamount");

                    String st[] = {"DID", thisdeduct_text, thisdeduct_price + "", thisdeduct_id + ""};
                    dt2.addRow(st);
                    thisdeduct += thisdeduct_price;

                }

                calsalary.UpdateTotalDiductions(thisdeduct);
                ldedtot.setText(calsalary.getTotalDiductions() + "");
                diductions.setText(calsalary.getTotalDiductions() + "");


            } catch (Exception e) {
                System.out.println("Error: " + e);
                e.printStackTrace();
            }




        }




    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advance;
    private javax.swing.JButton badd1;
    private javax.swing.JButton badd2;
    private javax.swing.JButton badd3;
    private javax.swing.JButton bclear1;
    private javax.swing.JButton bremove1;
    private javax.swing.JButton bremove2;
    private javax.swing.JButton bremove3;
    private javax.swing.JButton bsave;
    private com.imal.practicalJcombSearchable.JComboPractical cmbadditional;
    private com.imal.practicalJcombSearchable.JComboPractical cmballowance;
    private com.imal.practicalJcombSearchable.JComboPractical cmbdeduction;
    private javax.swing.JLabel diductions;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel ladditioncost;
    private javax.swing.JLabel laddtotal;
    private javax.swing.JLabel lallfinal;
    private javax.swing.JLabel lalltot;
    private javax.swing.JLabel lba;
    private javax.swing.JLabel lbalbasic;
    private javax.swing.JLabel lbsalary;
    private javax.swing.JTextField ldedamount;
    private javax.swing.JLabel ldedtot;
    private javax.swing.JLabel lempno;
    private javax.swing.JLabel lepfcompany;
    private javax.swing.JLabel lepfemployee;
    private javax.swing.JLabel lepfno;
    private javax.swing.JLabel letf;
    private javax.swing.JLabel lfinalsalary;
    private javax.swing.JLabel lga;
    private javax.swing.JList listemp;
    private javax.swing.JLabel lmsgmain;
    private javax.swing.JLabel lnprate1;
    private javax.swing.JLabel lnprate2;
    private javax.swing.JLabel lnptotal1;
    private javax.swing.JLabel lnptotal2;
    private javax.swing.JLabel lotamount;
    private javax.swing.JTextField lothrs;
    private javax.swing.JLabel lotrate;
    private javax.swing.JLabel lsalepf;
    private javax.swing.JLabel ltotdeductions;
    private javax.swing.JLabel ltotearnings;
    private javax.swing.JLabel ltype;
    private com.toedter.calendar.JMonthChooser mcmonth;
    private javax.swing.JLabel payee;
    private javax.swing.JScrollPane scrollemp;
    private javax.swing.JTextField taddamount;
    private javax.swing.JTextField taddqty;
    private javax.swing.JTextField tallowance;
    private javax.swing.JTable tbldeductions;
    private javax.swing.JTable tblearnings;
    private javax.swing.JTextField tename;
    private javax.swing.JTextField tnpdays1;
    private javax.swing.JTextField tnpdays2;
    private com.toedter.calendar.JYearChooser ycyear;
    // End of variables declaration//GEN-END:variables
}

class details {

    public int ID;
    public double value;
    public String textval;

    @Override
    public String toString() {
        return textval;
    }
}
