/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Designation;

/**
 *
 * @author Gihan
 */
public final class DesignationUI extends javax.swing.JFrame {
    int updateid;
    
    
    /**
     * Creates new form DesignationUI
     */
    public DesignationUI() {
        initComponents();
        bedit.setEnabled(false);
        bdeact.setEnabled(false);
        loadTable(Designation.showAllDesignations());
        //loadTable(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tdesignation = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldesignation = new javax.swing.JTable();
        bedit = new javax.swing.JButton();
        bdeact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Designation Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Designation");

        tdesignation.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tdesignation.setForeground(new java.awt.Color(0, 153, 255));

        badd.setText("Add+");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        tbldesignation.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbldesignation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldesignation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldesignation.setRowHeight(21);
        tbldesignation.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tbldesignation.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tbldesignation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldesignationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldesignation);
        tbldesignation.getColumnModel().getColumn(0).setMinWidth(50);
        tbldesignation.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbldesignation.getColumnModel().getColumn(0).setMaxWidth(50);

        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bdeact.setText("Diactivate");
        bdeact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tdesignation))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bedit, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdeact, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdeact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-372)/2, (screenSize.height-525)/2, 372, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        if(!tdesignation.getText().trim().equals("")){
            Designation designation = new Designation();
            designation.setDesignation(tdesignation.getText());
                if(designation.addDesignation()){
                    JOptionPane.showMessageDialog(null, "Done! Added Successfully!", "Done!", 1);
                   loadTable(Designation.showAllDesignations());
                    clearAll();
                }else{
                    JOptionPane.showMessageDialog(null, "Error While Adding Designation!", "Error!", 0);
                }
            
        }else{
            JOptionPane.showMessageDialog(null, "Type the Designation to Add!", "Warning!", 2);
        }
    }//GEN-LAST:event_baddActionPerformed

    private void tbldesignationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldesignationMouseClicked
        badd.setEnabled(false);
        bedit.setEnabled(true);
        bdeact.setEnabled(true);
        
        try {
            updateid = Integer.parseInt(tbldesignation.getValueAt(tbldesignation.getSelectedRow(), 0).toString());
            tdesignation.setText(tbldesignation.getValueAt(tbldesignation.getSelectedRow(), 1).toString());
        } catch (Exception e) {
            System.out.println("No Record Selected! " + e);
        }
        
        
        
    }//GEN-LAST:event_tbldesignationMouseClicked

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        if(updateid != 0){
            if(!tdesignation.getText().trim().equals("")){
                Designation designation = new Designation();
                designation.setDesignation(tdesignation.getText());
                    if(designation.updateDesignation(updateid)){
                        JOptionPane.showMessageDialog(null, "Done! Updated Successfully!", "Done!", 1);
                        loadTable(Designation.showAllDesignations());
                        clearAll();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error While Updating Designation!", "Error!", 0);
                    }
            
            }else{
                JOptionPane.showMessageDialog(null, "Type the Designation to Update!", "Warning!", 2);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select an Designation From Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bdeactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeactActionPerformed
        if(updateid != 0){
            if(JOptionPane.showConfirmDialog(null, "Sure to Deactivate Designation No " + updateid + "?", "Warning!", 0, 1) == 0){
                Designation designation = new Designation();
                    if(designation.deactivateDesignation(updateid)){
                        loadTable(Designation.showAllDesignations());
                        JOptionPane.showMessageDialog(null, "Done! Deactivated Designation No: " + updateid, "Done!", 1);
                    }else{
                        JOptionPane.showMessageDialog(null, "Error While Deactivating Designation!", "Error!", 0);
                    }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select Designation to Deactivate!", "Warning!", 2);
        }
    }//GEN-LAST:event_bdeactActionPerformed
    
    void loadTable(ResultSet rs){
        
        DefaultTableModel dt = (DefaultTableModel) tbldesignation.getModel();
        dt.setRowCount(0);
        
        try {
            while(rs.next()){
               ArrayList vec = new ArrayList();
                vec.add(rs.getInt("Designation_ID"));
                vec.add(rs.getString("Designation"));
                
                dt.addRow(vec.toArray()); 
            }
                    
        } catch (Exception e) {
            System.out.println("Error From loadTable Method: " + e);
        }
        
    }
    
    
    
    void clearAll(){
        tdesignation.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DesignationUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bdeact;
    private javax.swing.JButton bedit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldesignation;
    private javax.swing.JTextField tdesignation;
    // End of variables declaration//GEN-END:variables
}
