/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SitewiseDesignationReport;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Designation;

/**
 *
 * @author Imal
 */
public class DesignationSelection extends javax.swing.JFrame {

    JTable payroll;
    int Year, month;

    public DesignationSelection() {
        initComponents();

        try {
            ResultSet rs = Designation.showAllDesignationsOrder();
            DefaultTableModel df = (DefaultTableModel) designations.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                ArrayList<Object> a = new ArrayList<>();
                a.add(rs.getString("Designation"));
                a.add(false);
                df.addRow(a.toArray());
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public DesignationSelection(JTable payroll, int year, int month) {
        this();
        date.setText(year + "/" + month);
        this.payroll = payroll;
        this.Year = year;
        this.month = month;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        designations = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ReportName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select the Designation");
        setResizable(false);

        designations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Designation", "    "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        designations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                designationsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                designationsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(designations);
        designations.getColumnModel().getColumn(1).setMinWidth(30);
        designations.getColumnModel().getColumn(1).setPreferredWidth(30);
        designations.getColumnModel().getColumn(1).setMaxWidth(30);

        jLabel1.setText("Designation wise PaySheet (Designation) for");

        jLabel2.setText("Rep Name");

        jButton1.setText("Print Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReportName, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-441)/2, (screenSize.height-516)/2, 441, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void designationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designationsMouseClicked
    }//GEN-LAST:event_designationsMouseClicked

    private void designationsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designationsMouseReleased
        ReportName.setText("");
        for (int i = 0; i < designations.getRowCount(); i++) {
            boolean b = Boolean.parseBoolean(designations.getValueAt(i, 1).toString());
            if (b) {
                String sep = ",";
                if (ReportName.getText().equals("")) {
                    sep = "";
                }
                ReportName.setText(ReportName.getText() + sep + designations.getValueAt(i, 0).toString());
            }

        }

    }//GEN-LAST:event_designationsMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!ReportName.getText().trim().equals("")) {
            final ArrayList<String> ar = new ArrayList<>();
            for (int i = 0; i < designations.getRowCount(); i++) {
                if ((Boolean.parseBoolean(designations.getValueAt(i, 1).toString()))) {
                    ar.add(designations.getValueAt(i, 0).toString());
                }

            }

            int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to print site full report", "Site-Full Report", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                Thread t = new Thread(new Runnable() {

                    @Override
                    public void run() {
                        new SitewiseDesignationReport(payroll, month, Year, ar, ReportName.getText()).printThisInvoice();
                    }
                });
                t.start();
            }

            this.dispose();
            JOptionPane.showMessageDialog(null, "Printing Started");
        } else {
            JOptionPane.showMessageDialog(null, "Unable to create Report please check whether some Designations are \n selected and the Report name has given", "REPORT PRINTING ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new DesignationSelection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ReportName;
    private javax.swing.JLabel date;
    private javax.swing.JTable designations;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
