/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.imal.practicalJcombSearchable.JCData;
import control.Datecontrol;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.OftnLogic;

/**
 *
 * @author Gihan
 */
public final class EmpregisterUI extends javax.swing.JPanel {

    int updateid;
    int comboid;
    int EmpNumber;

    /**
     * Creates new form EmpregisterUI
     */
    public EmpregisterUI() {
        initComponents();
        tfname.grabFocus();
        bupdate.setEnabled(false);
        bdeativate.setEnabled(false);


        OftnLogic.Sites(cmbsite);
        OftnLogic.Designation(cmbdesignation);
        OftnLogic.LoadEmpType(cmbtype);
        OftnLogic.Division(cmbdivision);
        OftnLogic.Banks(cmbank);
        OftnLogic.BankBranch(cmbranch);
        Object ob = cmbank.getSelectedItem();
        if (ob != null) {
            OftnLogic.bankID = ((OftnLogic.Details) ob).ID;
            lbankno.setText(((OftnLogic.Details) ob).ID);
        }
        ob = cmbranch.getSelectedItem();
        if (ob != null) {
            lbranchno2.setText(((OftnLogic.Details) ob).ID);
        }
        loadTable(Employee.getEmployees(1));

//        loadTable(null);
//        loadComboData(null, cmbtype);
//        loadComboData(null, cmbdesignation);
//        loadComboData(null, cmbdivision);
//        loadComboData(null, cmbsite);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tlname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        taddno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tcity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tconhome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tconmobi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tnic = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbpaytype = new com.imal.practicalJcombSearchable.JComboPractical();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tempno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tepfno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dtdate = new com.toedter.calendar.JDateChooser();
        cmbtype = new com.imal.practicalJcombSearchable.JComboPractical();
        cmbdesignation = new com.imal.practicalJcombSearchable.JComboPractical();
        cmbdivision = new com.imal.practicalJcombSearchable.JComboPractical();
        cmbsite = new com.imal.practicalJcombSearchable.JComboPractical();
        jLabel20 = new javax.swing.JLabel();
        cmbank = new com.imal.practicalJcombSearchable.JComboPractical();
        jLabel21 = new javax.swing.JLabel();
        cmbranch = new com.imal.practicalJcombSearchable.JComboPractical();
        jLabel17 = new javax.swing.JLabel();
        taccno = new javax.swing.JTextField();
        lbankno = new javax.swing.JLabel();
        lbranchno2 = new javax.swing.JLabel();
        baddemp = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdeativate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemp = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        bclear = new javax.swing.JButton();
        bclear1 = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("First / Middle Name");

        tfname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tfname.setForeground(new java.awt.Color(51, 51, 51));
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfnameKeyReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Last Name");

        tlname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tlname.setForeground(new java.awt.Color(51, 51, 51));
        tlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tlnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tlnameKeyReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Address No / Street");

        taddno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        taddno.setForeground(new java.awt.Color(51, 51, 51));
        taddno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taddnoKeyPressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("City");

        tcity.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tcity.setForeground(new java.awt.Color(51, 51, 51));
        tcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcityKeyPressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Contact No (Home)");

        tconhome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tconhome.setForeground(new java.awt.Color(51, 51, 51));
        tconhome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tconhomeKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Contact No (Mobile)");

        tconmobi.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tconmobi.setForeground(new java.awt.Color(51, 51, 51));
        tconmobi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tconmobiKeyPressed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText("NIC No");

        tnic.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tnic.setForeground(new java.awt.Color(51, 51, 51));
        tnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnicKeyPressed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("Pay Type");

        cmbpaytype.setForeground(new java.awt.Color(102, 0, 0));
        cmbpaytype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BANK", "CASH" }));
        cmbpaytype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbpaytype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbpaytypeItemStateChanged(evt);
            }
        });
        cmbpaytype.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbpaytypePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tlname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taddno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tconmobi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tconhome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcity))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tnic))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbpaytype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfname, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tlname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taddno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tconhome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tconmobi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tnic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(cmbpaytype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Emp.No");

        tempno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tempno.setForeground(new java.awt.Color(51, 51, 51));
        tempno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempnoKeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("EPF. No");

        tepfno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tepfno.setForeground(new java.awt.Color(51, 51, 51));
        tepfno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tepfnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tepfnoKeyReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Designation");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Division");

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText("Site");

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Emp. Type");

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 0));
        jLabel18.setText("Joined Date");

        dtdate.setForeground(new java.awt.Color(51, 51, 51));
        dtdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dtdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtdatePropertyChange(evt);
            }
        });

        cmbtype.setForeground(new java.awt.Color(102, 0, 0));
        cmbtype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cmbdesignation.setForeground(new java.awt.Color(102, 0, 0));
        cmbdesignation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cmbdivision.setForeground(new java.awt.Color(102, 0, 0));
        cmbdivision.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setText("Bank");

        cmbank.setForeground(new java.awt.Color(102, 0, 0));
        cmbank.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbankItemStateChanged(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setText("Branch");

        cmbranch.setForeground(new java.awt.Color(102, 0, 0));
        cmbranch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbranchItemStateChanged(evt);
            }
        });
        cmbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbranchActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setText("Acc. No");

        taccno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        taccno.setForeground(new java.awt.Color(51, 51, 51));
        taccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taccnoKeyPressed(evt);
            }
        });

        lbankno.setBackground(new java.awt.Color(51, 51, 51));
        lbankno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbankno.setForeground(new java.awt.Color(102, 0, 0));
        lbankno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbankno.setText("0000");
        lbankno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        lbranchno2.setBackground(new java.awt.Color(51, 51, 51));
        lbranchno2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbranchno2.setForeground(new java.awt.Color(102, 0, 0));
        lbranchno2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbranchno2.setText("0000");
        lbranchno2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbranchno2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(taccno, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbdivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbsite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 69, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbankno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addComponent(jLabel14))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbdesignation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbtype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(tepfno, javax.swing.GroupLayout.Alignment.LEADING))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tepfno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(cmbtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(cmbdesignation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(cmbdivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(cmbsite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(dtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbank, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbankno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbranchno2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taccno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        baddemp.setText("Add Employee");
        baddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddempActionPerformed(evt);
            }
        });

        bupdate.setText("Update Details");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bdeativate.setText("Deactivate Employee");
        bdeativate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeativateActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tblemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblemp.setForeground(new java.awt.Color(51, 51, 51));
        tblemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp.No", "EPF No", "Full Name", "Designation", "Site", "Address", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblemp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblemp.setRowHeight(21);
        tblemp.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblemp.getTableHeader().setReorderingAllowed(false);
        tblemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblemp);
        tblemp.getColumnModel().getColumn(0).setMinWidth(60);
        tblemp.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblemp.getColumnModel().getColumn(0).setMaxWidth(60);
        tblemp.getColumnModel().getColumn(1).setMinWidth(60);
        tblemp.getColumnModel().getColumn(1).setPreferredWidth(60);
        tblemp.getColumnModel().getColumn(1).setMaxWidth(60);
        tblemp.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblemp.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblemp.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblemp.getColumnModel().getColumn(5).setPreferredWidth(250);
        tblemp.getColumnModel().getColumn(6).setPreferredWidth(100);

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(128, 128, 128));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgtop.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bclear.setText("Clear");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        bclear1.setText("Delete unused Emp Details");
        bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bdeativate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bclear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(bclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(baddemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(baddemp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdeativate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {baddemp, bdeativate, bupdate});

    }// </editor-fold>//GEN-END:initComponents

    private void tfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tlname.grabFocus();
        }
    }//GEN-LAST:event_tfnameKeyPressed

    private void tlnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            taddno.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            tempno.grabFocus();
        }
    }//GEN-LAST:event_tlnameKeyPressed

    private void taddnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taddnoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tcity.grabFocus();
        }
    }//GEN-LAST:event_taddnoKeyPressed

    private void tcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tconhome.grabFocus();
        }
    }//GEN-LAST:event_tcityKeyPressed

    private void tconhomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tconhomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tconmobi.grabFocus();
        }
    }//GEN-LAST:event_tconhomeKeyPressed

    private void tconmobiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tconmobiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tnic.grabFocus();
        }
    }//GEN-LAST:event_tconmobiKeyPressed

    private void tnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnicKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbank.grabFocus();
        }
    }//GEN-LAST:event_tnicKeyPressed

    private void taccnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taccnoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tempno.grabFocus();
        }
    }//GEN-LAST:event_taccnoKeyPressed

    private void tempnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempnoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tepfno.grabFocus();
        }
    }//GEN-LAST:event_tempnoKeyPressed

    private void tepfnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tepfnoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbtype.grabFocus();
        }
    }//GEN-LAST:event_tepfnoKeyPressed

    private void baddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddempActionPerformed
        if (formCheck()) {
            if (JOptionPane.showConfirmDialog(null, "Sure to Add?", "Question", 0, 1) == 0) {
                if ((cmbank.getItemCount() > 0 && cmbranch.getItemCount() > 0) || (cmbpaytype.getSelectedItem().toString().equals("CASH"))) {




                    Employee employee = new Employee();
                    Datecontrol datecontrol = new Datecontrol();

                    employee.setFmname(tfname.getText());
                    employee.setLname(tlname.getText());
                    employee.setAddno(taddno.getText());
                    employee.setCity(tcity.getText());
                    employee.setConhome(tconhome.getText());
                    employee.setConmobi(tconmobi.getText());
                    employee.setNicno(tnic.getText());
                    employee.setPayType(cmbpaytype.getSelectedItem().toString());
                    if (cmbank.getSelectedItem() != null) {
                        OftnLogic.Details d = ((OftnLogic.Details) cmbank.getSelectedItem());
                        employee.setBank(d.name);
                        employee.setBankNumber(d.ID);
                    }
                    if (cmbranch.getSelectedItem() != null) {
                        OftnLogic.Details d1 = ((OftnLogic.Details) cmbranch.getSelectedItem());
                        employee.setBranch(d1.name);
                        employee.setBranchNumber(d1.ID);
                    }
                    employee.setAccno(taccno.getText());

                    employee.setEmpno(Integer.parseInt(tempno.getText()));
                    employee.setEpfno(Integer.parseInt(tepfno.getText()));
//Get values from comboboxes and pass to model class-------------------------------------------------
                    employee.setEtype(cmbtype.getSelectedDataItemID());
                    employee.setDesignation(cmbdesignation.getSelectedDataItemID());
                    employee.setDivision(cmbdivision.getSelectedDataItemID());
                    employee.setSite(cmbsite.getSelectedDataItemID());
//Get Dates from control layer-----------------------------------------------------------------------
                    employee.setJoineddate(datecontrol.getSelectedDate(dtdate));
                    employee.setRegdate(datecontrol.getCurrentDate());

                    if (employee.addEmployee()) {
                        JOptionPane.showMessageDialog(null, "Done! Successfully Added Employee!", "Done!", 1);
                        clearAll();
                        loadTable(Employee.getEmployees(1));

                    } else {
                        JOptionPane.showMessageDialog(null, "Error While Adding Employee Data!", "Error!", 0);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select the Bank and Branch Properly", "SELECTION ERROR", JOptionPane.WARNING_MESSAGE);
            }


        } else {
            paintTextfields();
            JOptionPane.showMessageDialog(null, "First & Last Name, Emp.No, EPF.No & Joined Date is Essential!", "Warning!", 2);
        }
    }//GEN-LAST:event_baddempActionPerformed

    private void tfnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyReleased
        paintNormal(tfname);
    }//GEN-LAST:event_tfnameKeyReleased

    private void tlnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlnameKeyReleased
        paintNormal(tlname);
    }//GEN-LAST:event_tlnameKeyReleased

    private void tempnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempnoKeyReleased
        paintNormal(tempno);
    }//GEN-LAST:event_tempnoKeyReleased

    private void tepfnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tepfnoKeyReleased
        paintNormal(tepfno);
    }//GEN-LAST:event_tepfnoKeyReleased

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        if (updateid != 0) {
            if ((cmbank.getItemCount() > 0 && cmbranch.getItemCount() > 0) || (cmbpaytype.getSelectedItem().toString().equals("CASH"))) {
                
                if (formCheck()) {
                    if (JOptionPane.showConfirmDialog(null, "Sure to Update?", "Question", 0, 1) == 0) {
                        Employee employee = new Employee();
                        Datecontrol datecontrol = new Datecontrol();

                        employee.setFmname(tfname.getText());
                        employee.setLname(tlname.getText());
                        employee.setAddno(taddno.getText());
                        employee.setCity(tcity.getText());
                        employee.setConhome(tconhome.getText());
                        employee.setConmobi(tconmobi.getText());
                        employee.setNicno(tnic.getText());

                        employee.setPayType(cmbpaytype.getSelectedItem().toString());
                        if (cmbank.getSelectedItem() != null) {
                            OftnLogic.Details d = ((OftnLogic.Details) cmbank.getSelectedItem());
                            employee.setBank(d.name);
                            employee.setBankNumber(d.ID);
                        }
                        if (cmbranch.getSelectedItem() != null) {
                            OftnLogic.Details d1 = ((OftnLogic.Details) cmbranch.getSelectedItem());
                            employee.setBranch(d1.name);
                            employee.setBranchNumber(d1.ID);
                        }

                        employee.setAccno(taccno.getText());
                        employee.setEmpno(Integer.parseInt(tempno.getText()));
                        employee.setEpfno(Integer.parseInt(tepfno.getText()));
//Get values from comboboxes and pass to model class-------------------------------------------------
                        employee.setEtype(cmbtype.getSelectedDataItemID());
                        employee.setDesignation(cmbdesignation.getSelectedDataItemID());
                        employee.setDivision(cmbdivision.getSelectedDataItemID());
                        employee.setSite(cmbsite.getSelectedDataItemID());
//Get Dates from control layer-----------------------------------------------------------------------
                        employee.setJoineddate(datecontrol.getSelectedDate(dtdate));
                        employee.setRegdate(datecontrol.getCurrentDate());

                        if (employee.updateEmployee(updateid)) {
                            JOptionPane.showMessageDialog(null, "Done! Successfully Updated Employee!", "Done!", 1);
                            clearAll();
                            loadTable(Employee.getEmployees(1));
                        } else {
                            JOptionPane.showMessageDialog(null, "Error While Updating Employee Data!", "Error!", 0);
                        }
                    }
                } else {
                    paintTextfields();
                    JOptionPane.showMessageDialog(null, "First & Last Name Essential!", "Warning!", 2);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Please select the Bank and Branch Properly", "SELECTION ERROR", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select an Employee From Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void tblempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempMouseClicked
        baddemp.setEnabled(false);
        bupdate.setEnabled(true);
        bdeativate.setEnabled(true);
        tempno.setEnabled(false);

        try {
            updateid = Integer.parseInt(tblemp.getValueAt(tblemp.getSelectedRow(), 0).toString());
        } catch (Exception e) {
            System.out.println("No Record Selected! " + e);
        }

        showFromTable(Employee.getCompleteDetailsEmp(updateid));

    }//GEN-LAST:event_tblempMouseClicked

    private void bdeativateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeativateActionPerformed
        if (updateid != 0) {
            if (JOptionPane.showConfirmDialog(null, "Sure to Deactivate Employee No " + updateid + "?", "Warning!", 0, 1) == 0) {
                Employee employee = new Employee();
                if (employee.deactivateEmployee(updateid)) {
                    JOptionPane.showMessageDialog(null, "Done! Deactivated Employee No: " + updateid, "Done!", 1);
                    loadTable(Employee.getEmployees(1));
                } else {
                    JOptionPane.showMessageDialog(null, "Error While Deactivating Employee!", "Error!", 0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select Employee to Deactivate!", "Warning!", 2);
        }
    }//GEN-LAST:event_bdeativateActionPerformed

    private void dtdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtdatePropertyChange
        paintNormal(tepfno);
    }//GEN-LAST:event_dtdatePropertyChange

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        clearAll();
    }//GEN-LAST:event_bclearActionPerformed

    private void bclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear1ActionPerformed
        if (updateid != 0) {
            Employee employee = new Employee();
            if (employee.deleteEmployee(updateid)) {
                JOptionPane.showMessageDialog(null, "Done! Successfully Deleted Employee!", "Done!", 1);
                clearAll();
                loadTable(Employee.getEmployees(1));

            } else {
                JOptionPane.showMessageDialog(null, "Error While Deleteing Employee Data!", "Error!", 0);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select Employee to Delete!", "Warning!", 2);
        }
    }//GEN-LAST:event_bclear1ActionPerformed

    private void cmbpaytypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbpaytypePropertyChange
        boolean b = cmbpaytype.getSelectedItem().toString().equals("BANK");

        cmbank.setEnabled(b);
        cmbranch.setEnabled(b);
        taccno.setEnabled(b);

    }//GEN-LAST:event_cmbpaytypePropertyChange

    private void cmbpaytypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbpaytypeItemStateChanged
        boolean b = cmbpaytype.getSelectedItem().toString().equals("BANK");

        cmbank.setEnabled(b);
        cmbranch.setEnabled(b);
        taccno.setEnabled(b);
    }//GEN-LAST:event_cmbpaytypeItemStateChanged

    private void cmbankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbankItemStateChanged
        OftnLogic.bankID = ((OftnLogic.Details) cmbank.getSelectedItem()).ID;

        OftnLogic.BankBranch(cmbranch);
        if (cmbranch.getSelectedItem() != null) {
            lbankno.setText(((OftnLogic.Details) cmbank.getSelectedItem()).ID);
            lbranchno2.setText(((OftnLogic.Details) cmbranch.getSelectedItem()).ID);
        } else {
            lbranchno2.setText("");
        }
    }//GEN-LAST:event_cmbankItemStateChanged

    private void cmbranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbranchItemStateChanged
    }//GEN-LAST:event_cmbranchItemStateChanged

    private void cmbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbranchActionPerformed
        Object d0 = cmbranch.getSelectedItem();
        if (d0 != null) {
            lbranchno2.setText((((OftnLogic.Details) d0).ID) + "");
        }

    }//GEN-LAST:event_cmbranchActionPerformed

    boolean formCheck() {
        boolean val = false;

        try {
            if (tfname.getText().trim().equals("") || tlname.getText().trim().equals("") || tempno.getText().trim().equals("") || tepfno.getText().trim().equals("") || dtdate.getDate().equals("")) {
                val = false;
            } else {
                val = true;
            }
        } catch (Exception e) {
            val = false;
        }

        return val;
    }

    void paintTextfields() {
        Color color1 = new Color(251, 195, 198);

        if (tfname.getText().trim().equals("")) {
            tfname.setBackground(color1);
        }
        if (tlname.getText().trim().equals("")) {
            tlname.setBackground(color1);

        }
        if (tempno.getText().trim().equals("")) {
            tempno.setBackground(color1);

        }
        if (tepfno.getText().trim().equals("")) {
            tepfno.setBackground(color1);

        }
        try {
            if (dtdate.getDate().equals("")) {
                dtdate.setBackground(color1);

            }
        } catch (Exception e) {
            dtdate.setBackground(color1);
        }
    }

    void paintNormal(JTextField tfield) {
        Color color2 = new Color(255, 255, 255);
        tfield.setBackground(color2);

    }

//When User click on an employee's record on table, that employee's details should display on relevant textfields and combo boxes
//Following method will takes the details from database and display on textfields
    void showFromTable(ResultSet rs) {
        if (updateid != 0) {
            try {
                if (rs.next()) {
                    EmpNumber = rs.getInt("EmpNumber");
                    tfname.setText(rs.getString("FMname"));
                    tlname.setText(rs.getString("Lname"));
                    taddno.setText(rs.getString("Add_nub"));
                    tcity.setText(rs.getString("City"));
                    tconhome.setText(rs.getString("ContactHome"));
                    tconmobi.setText(rs.getString("contactMobile"));
                    tnic.setText(rs.getString("NIC"));
                    if (rs.getString("PayType").equals("BANK")) {
                        OftnLogic.Details d = new OftnLogic.Details();
                        d.ID = rs.getString("bankcode");
                        cmbank.setSelectedItem(d);
                        lbankno.setText(rs.getString("bankcode"));

                        lbranchno2.setText(rs.getString("branchcode"));
                        d.ID = rs.getString("branchcode");
                        cmbranch.setSelectedItem(d);
                    }
                    cmbpaytype.setSelectedItem(rs.getString("PayType"));

                    taccno.setText(rs.getString("ccountnumber"));
                    tempno.setText(rs.getString("EmpNumber"));
                    tepfno.setText(rs.getString("EpfNumber"));
                    JCData data = new JCData();
                    int i = rs.getInt("Emp_TypeID");
                    if (i == 1) {
                        data.setDisplayMember("SITE");
                    } else if (i == 2) {
                        data.setDisplayMember("OFFICE");
                    }
                    data.setValueMember(i);
                    cmbtype.setSelectedItem(data);
                    data.setDisplayMember(rs.getString("Designation"));
                    data.setValueMember(rs.getInt("Designation_ID"));
                    cmbdesignation.setSelectedItem(data);
                    data.setDisplayMember(rs.getString("DivisionName"));
                    data.setValueMember(rs.getInt("DivisionID"));
                    cmbdivision.setSelectedItem(data);
                    data.setDisplayMember(rs.getString("SiteLocation"));
                    data.setValueMember(rs.getInt("SiteID"));
                    cmbsite.setSelectedItem(data);
                    dtdate.setDate(rs.getDate("JontDate"));
                }

            } catch (Exception e) {
                System.out.println("Error From loadTable Method: " + e);
            }
        }
    }

    void loadTable(ResultSet rs) {
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblemp.getModel();

        try {
            while (rs.next()) {
                ArrayList vec = new ArrayList();
                vec.add(rs.getInt("EmpNumber"));
                vec.add(rs.getInt("EpfNumber"));
                vec.add(rs.getString("FMname") + " " + rs.getString("Lname"));
                vec.add(rs.getString("Designation"));
                vec.add(rs.getString("Site_location"));
                vec.add(rs.getString("Add_nub") + " " + rs.getString("City"));
                vec.add(rs.getString("contactMobile"));
                dt.addRow(vec.toArray());
            }

        } catch (Exception e) {
            System.out.println("Error From loadTable Method: " + e);
        }

    }

    void clearTable() {
        DefaultTableModel dt = (DefaultTableModel) tblemp.getModel();
        int rows = tblemp.getRowCount();
        for (int x = 0; x < rows; x++) {
            dt.removeRow(0);
        }

    }

    void loadComboData(ResultSet rs, JComboBox cmb) {

        try {
            while (rs.next()) {
                String combodata = rs.getString("");
                cmb.addItem(combodata);
            }
        } catch (Exception e) {
            System.out.println("Error From loadComboData Method: " + e);
        }

    }

    void clearAll() {
        tfname.setText("");
        tlname.setText("");
        taddno.setText("");
        tcity.setText("");
        tconhome.setText("");
        tconmobi.setText("");
        tnic.setText("");

        taccno.setText("");
        tempno.setText("");
        tepfno.setText("");
        lbankno.setText("");
        lbranchno2.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baddemp;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bclear1;
    private javax.swing.JButton bdeativate;
    private javax.swing.JButton bupdate;
    private com.imal.practicalJcombSearchable.JComboPractical cmbank;
    private com.imal.practicalJcombSearchable.JComboPractical cmbdesignation;
    private com.imal.practicalJcombSearchable.JComboPractical cmbdivision;
    private com.imal.practicalJcombSearchable.JComboPractical cmbpaytype;
    private com.imal.practicalJcombSearchable.JComboPractical cmbranch;
    private com.imal.practicalJcombSearchable.JComboPractical cmbsite;
    private com.imal.practicalJcombSearchable.JComboPractical cmbtype;
    private com.toedter.calendar.JDateChooser dtdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbankno;
    private javax.swing.JLabel lbranchno2;
    private javax.swing.JTextField taccno;
    private javax.swing.JTextField taddno;
    private javax.swing.JTable tblemp;
    private javax.swing.JTextField tcity;
    private javax.swing.JTextField tconhome;
    private javax.swing.JTextField tconmobi;
    private javax.swing.JTextField tempno;
    private javax.swing.JTextField tepfno;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tlname;
    private javax.swing.JTextField tnic;
    // End of variables declaration//GEN-END:variables
}
