/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.DB;

/**
 *
 * @author Imal
 */
public class historyfix extends javax.swing.JFrame {

    /**
     * Creates new form historyfix
     */
    public historyfix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histor Fix");
        setResizable(false);

        jButton1.setText("Fix History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("One Time Only...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-391)/2, (screenSize.height-264)/2, 391, 264);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPasswordField pwd = new JPasswordField(10);
        int action = JOptionPane.showConfirmDialog(null, pwd, "Enter Password", JOptionPane.OK_CANCEL_OPTION);

        if (new String(pwd.getPassword()).equals("5487hsfix")) {
            try {

                ResultSet rs = DB.getData("SELECT payRollNum,EmpNumber FROM payroll");
                while (rs.next()) {
                    ResultSet rso = DB.getData("SELECT bankcode,branchcode,SiteID,Designation_ID,ccountnumber FROM allempdetails WHERE EmpNumber = '" + (rs.getString("EmpNumber")) + "'");
                    rso.first();

                    String payrolId = rs.getString("payRollNum");
                    String bankcode = "'" + (rso.getString("bankcode")) + "'";
                    String branchcode = "'" + (rso.getString("branchcode")) + "'";
                    String Accountnub = "'" + (rso.getString("ccountnumber")) + "'";
                    String Designation = "'" + (rso.getString("Designation_ID")) + "'";
                    String Site = "'" + (rso.getString("SiteID")) + "'";

                    if (branchcode.trim().replace("'", "").toLowerCase().equals("null")) {
                        bankcode = "Bankcode";
                        branchcode = "branchCode";
                        Accountnub = "Account_numb";
                    }

                    String sql = "insert into emppayroldata "
                            + "(payRollNum, "
                            + "Designation_id, "
                            + "Site_id, "
                            + "Bankcode, "
                            + "branchCode, "
                            + "Account_numb "
                            + ") "
                            + "values "
                            + "('" + payrolId + "', "
                            + "" + Designation + ", "
                            + "" + Site + ", "
                            + " " + bankcode + ", "
                            + " " + branchcode + ", "
                            + " " + Accountnub + " "
                            + " )";
                    System.out.println(sql);
                    DB.setData(sql);

                    ResultSet rs1 = DB.getData("SELECT* FROM emp_site WHERE MONTH(Time_range) = '9' && is_active = '0' &&  EmployeeEmpNumber < 1510  GROUP BY EmployeeEmpNumber ORDER BY EmployeeEmpNumber");


                }


            } catch (Exception e) {
                System.out.println(e);
            }
            System.out.println("DONE FIXED!!!");
        } else {
            JOptionPane.showMessageDialog(null, "You Can't do This?", "Warning!", 2);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JPasswordField pwd = new JPasswordField(10);
        int action = JOptionPane.showConfirmDialog(null, pwd, "Enter Password", JOptionPane.OK_CANCEL_OPTION);

        if (new String(pwd.getPassword()).equals("5487hsfix2")) {
            try {
                ResultSet rs1 = DB.getData("SELECT EmployeeEmpNumber,site_ID FROM emp_site WHERE MONTH(Time_range) = '9' && is_active = '0' &&  EmployeeEmpNumber < 1510  GROUP BY EmployeeEmpNumber ORDER BY EmployeeEmpNumber");
                while (rs1.next()) {

                    ResultSet rs2 = DB.getData("SELECT payRollNum FROM payroll WHERE MONTH = '7' && EmpNumber = '" + (rs1.getString("EmployeeEmpNumber")) + "' ");
                    while (rs2.next()) {
                        System.out.println("payroolnum" + rs2.getString("payRollNum"));
                        DB.setData("UPDATE emppayroldata SET Site_id = '" + (rs1.getString("site_ID")) + "' WHERE payRollNum = '" + rs2.getString("payRollNum") + "'");
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            System.out.println("DONE FIXED!!!");
        } else {
            JOptionPane.showMessageDialog(null, "You Can't do This?", "Warning!", 2);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historyfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historyfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historyfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historyfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new historyfix().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
