/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.SetDB;
import model.User;

/**
 *
 * @author Gihan
 */
public class Login extends javax.swing.JFrame {
    MainUI1 mainui;
    User user;
    
    /**
     * Creates new form Login
     */
    public Login(MainUI1 mainwin) {
        initComponents();
        this.mainui = mainwin;
        tusername.grabFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        blogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 41, -1, -1));

        tusername.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tusername.setForeground(new java.awt.Color(102, 102, 102));
        tusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tusernameKeyPressed(evt);
            }
        });
        jPanel1.add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 32, 135, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 89, -1, -1));

        tpassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tpassword.setForeground(new java.awt.Color(102, 102, 102));
        tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpasswordKeyPressed(evt);
            }
        });
        jPanel1.add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 80, 135, 31));

        blogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blogin.setText("Login");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel1.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginimage.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-354)/2, (screenSize.height-249)/2, 354, 249);
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        user = new User();
        
        if(tusername.getText().trim().equals("") || tpassword.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Fill All Values", "Warning!", 2); 
        }else{
            if(user.userValidate(tusername.getText().replace("'", ""), (new String(tpassword.getPassword())).replace("'", ""))){ 
                mainui = new MainUI1();
                mainui.setLogUser(tusername.getText(), mainui); 
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Username or Password are incorrect, Try again!", "Error!", 0);
                tusername.setText("");
                tpassword.setText("");
                tusername.grabFocus();
            }
        }
        
        
        
    }//GEN-LAST:event_bloginActionPerformed

    private void tusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tusernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tpassword.grabFocus();
        }
    }//GEN-LAST:event_tusernameKeyPressed

    private void tpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            bloginActionPerformed(null);
        }
    }//GEN-LAST:event_tpasswordKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SetDB set = new SetDB();
        set.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
