/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Printbankwisetotal;
import control.Printbankwisetotal2;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Branch;

/**
 *
 * @author Gihan
 */
public class Reportbanwise extends javax.swing.JFrame {

    Branch branch;
    Printbankwisetotal printbankreport;
    Printbankwisetotal2 printbankreport2;
    
    int totalrecords;
    double totalbankamount;
    double totalbankamount2;
    
    String selectbcode;
    String selectbname;

    /**
     * Creates new form Reportbanwise
     */
    public Reportbanwise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbanks = new javax.swing.JTable();
        uprint = new javax.swing.JButton();
        ycyear = new com.toedter.calendar.JYearChooser();
        mcmonth = new com.toedter.calendar.JMonthChooser();
        jLabel3 = new javax.swing.JLabel();
        ltotrecords = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ltotamount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ltotpackamount = new javax.swing.JLabel();
        bview1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsub = new javax.swing.JTable();
        uprint2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbank = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bank Wise Report");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Year-Month");

        bview.setText("View Main");
        bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewActionPerformed(evt);
            }
        });

        tblbanks.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblbanks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B.Code", "Bank", "Records", "Total Amount", "Total Pack.Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbanks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblbanks.setRowHeight(21);
        tblbanks.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tblbanks.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblbanks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbanksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbanks);
        tblbanks.getColumnModel().getColumn(0).setMinWidth(80);
        tblbanks.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblbanks.getColumnModel().getColumn(0).setMaxWidth(80);
        tblbanks.getColumnModel().getColumn(2).setMinWidth(80);
        tblbanks.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblbanks.getColumnModel().getColumn(2).setMaxWidth(80);
        tblbanks.getColumnModel().getColumn(3).setMinWidth(80);
        tblbanks.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblbanks.getColumnModel().getColumn(3).setMaxWidth(80);
        tblbanks.getColumnModel().getColumn(4).setMinWidth(80);
        tblbanks.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblbanks.getColumnModel().getColumn(4).setMaxWidth(80);

        uprint.setText("Print Main Table");
        uprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uprintActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total Records");

        ltotrecords.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltotrecords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotrecords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total Bank Amount");

        ltotamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltotamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Total Pack. Amount");

        ltotpackamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ltotpackamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotpackamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bview1.setText("View Sub");
        bview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bview1ActionPerformed(evt);
            }
        });

        tblsub.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblsub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp.No", "Name", "Acc.No", "F.Salary", "Pack.Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsub.setRowHeight(21);
        jScrollPane2.setViewportView(tblsub);
        tblsub.getColumnModel().getColumn(0).setMinWidth(60);
        tblsub.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblsub.getColumnModel().getColumn(0).setMaxWidth(60);
        tblsub.getColumnModel().getColumn(2).setMinWidth(100);
        tblsub.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblsub.getColumnModel().getColumn(2).setMaxWidth(100);
        tblsub.getColumnModel().getColumn(3).setMinWidth(80);
        tblsub.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblsub.getColumnModel().getColumn(3).setMaxWidth(80);
        tblsub.getColumnModel().getColumn(4).setMinWidth(80);
        tblsub.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblsub.getColumnModel().getColumn(4).setMaxWidth(80);

        uprint2.setText("Print Sub Table");
        uprint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uprint2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Bank:");

        lbank.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Code:");

        lcode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ycyear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mcmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(bview1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uprint2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ltotpackamount, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ltotrecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ltotamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbank, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bview1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(mcmonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ycyear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(lbank, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(uprint, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uprint2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ltotrecords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ltotamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ltotpackamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1147)/2, (screenSize.height-574)/2, 1147, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void bviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewActionPerformed
        branch = new Branch();
        loadTable(branch.getBankWiseTotal(ycyear.getYear(), mcmonth.getMonth() + 1));


    }//GEN-LAST:event_bviewActionPerformed

    private void tblbanksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbanksMouseClicked
    }//GEN-LAST:event_tblbanksMouseClicked

    private void uprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uprintActionPerformed
        if (tblbanks.getRowCount() > 0) {
            
            if (JOptionPane.showConfirmDialog(null, "Sure to Print the Main Table Data?", "Question", 0, 3) == 0) {
                printbankreport = new Printbankwisetotal();
                printbankreport.setYear(ycyear.getYear());
                printbankreport.setMonth(mcmonth.getMonth() + 1);
                printbankreport.setTotrecords(totalrecords);
                printbankreport.setTotamount(totalbankamount);
                printbankreport.setTotpackamount(totalbankamount2);
                printbankreport.printThisInvoice(tblbanks);
            }


        } else {
            JOptionPane.showMessageDialog(null, "Main Table is Empty, Check the Year & Month!", "Warning!", 2);
        }
    }//GEN-LAST:event_uprintActionPerformed

    private void bview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bview1ActionPerformed
        if(tblbanks.getRowCount() > 0){
            if(tblbanks.getSelectedRow() != -1){
                selectbcode = tblbanks.getValueAt(tblbanks.getSelectedRow(), 0).toString();
                selectbname = tblbanks.getValueAt(tblbanks.getSelectedRow(), 1).toString();
                lbank.setText(selectbname);
                lcode.setText(selectbcode);
                
                branch = new Branch();
                loadTable2(branch.getBankWiseTotal2(ycyear.getYear(), mcmonth.getMonth() + 1, selectbcode));
                
            }else{
                JOptionPane.showMessageDialog(null, "Select the Row from Main Table!", "Warning!", 2);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Main Table is Empty, First Get Data to Main Table!", "Warning!", 2);
        }
        
    }//GEN-LAST:event_bview1ActionPerformed

    private void uprint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uprint2ActionPerformed
        double totsal = 0.0;
        double packsal = 0.0;
        
        if (tblsub.getRowCount() > 0) {
            for(int x = 0; x < tblsub.getRowCount(); x++){
                totsal += Double.parseDouble(tblsub.getValueAt(x, 3).toString());
                packsal += Double.parseDouble(tblsub.getValueAt(x, 4).toString());
            }
            if (JOptionPane.showConfirmDialog(null, "Sure to Print the " + selectbname + " Data?", "Question", 0, 3) == 0) {
                printbankreport2 = new Printbankwisetotal2();
                printbankreport2.setYear(ycyear.getYear());
                printbankreport2.setMonth(mcmonth.getMonth() + 1);
                printbankreport2.setBankname(selectbname);
                printbankreport2.setTotrecords(tblsub.getRowCount());
                printbankreport2.setTotamount(totsal);
                printbankreport2.setTotpackamount(packsal);
                printbankreport2.printThisInvoice(tblsub);
            }


        } else {
            JOptionPane.showMessageDialog(null, "Sub Table is Empty, First Get Data to Print!", "Warning!", 2);
        }
    }//GEN-LAST:event_uprint2ActionPerformed

    void loadTable(ResultSet rs) {
        clearTable(tblbanks);
        DefaultTableModel dt = (DefaultTableModel) tblbanks.getModel();

        totalrecords = 0;
        totalbankamount = 0.0;
        totalbankamount2 = 0.0;

        try {
            while (rs.next()) {
                ArrayList vec = new ArrayList();
                totalrecords += rs.getInt("numofrecs");
                totalbankamount += rs.getDouble("totsalary");
                totalbankamount2 += rs.getDouble("totpack");

                vec.add(rs.getString("bankcode"));
                vec.add(rs.getString("bankname"));
                vec.add(rs.getInt("numofrecs"));
                vec.add(rs.getDouble("totsalary"));
                vec.add(rs.getDouble("totpack"));
                dt.addRow(vec.toArray());
            }
            ltotrecords.setText("" + totalrecords);
            ltotamount.setText("" + totalbankamount);
            ltotpackamount.setText("" + totalbankamount2);

        } catch (Exception e) {
            System.out.println("Error From loadTable Method: " + e);
        }

    }
    
    void loadTable2(ResultSet rs) {
        clearTable(tblsub);
        DefaultTableModel dt = (DefaultTableModel) tblsub.getModel();
        
        try {
            while (rs.next()) {
                ArrayList vec = new ArrayList();
                
                vec.add(rs.getInt("EmpNumber"));
                vec.add(rs.getString("FMname") + " " + rs.getString("Lname"));
                vec.add(rs.getString("Account_number"));
                vec.add(rs.getDouble("FinalSalary"));
                vec.add(rs.getDouble("PackSal"));
                dt.addRow(vec.toArray());
            }

        } catch (Exception e) {
            System.out.println("Error From loadTable2 Method: " + e);
        }

    }

    void clearTable(JTable tbl) {
        DefaultTableModel dt = (DefaultTableModel) tbl.getModel();
        int rows = tbl.getRowCount();
        for (int x = 0; x < rows; x++) {
            dt.removeRow(0);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportbanwise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportbanwise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportbanwise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportbanwise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reportbanwise().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bview;
    private javax.swing.JButton bview1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbank;
    private javax.swing.JLabel lcode;
    private javax.swing.JLabel ltotamount;
    private javax.swing.JLabel ltotpackamount;
    private javax.swing.JLabel ltotrecords;
    private com.toedter.calendar.JMonthChooser mcmonth;
    private javax.swing.JTable tblbanks;
    private javax.swing.JTable tblsub;
    private javax.swing.JButton uprint;
    private javax.swing.JButton uprint2;
    private com.toedter.calendar.JYearChooser ycyear;
    // End of variables declaration//GEN-END:variables
}
