/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PrintSiteCompare;
import control.Printcomparereport;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DB;
import model.PayRoll;
import model.Site;

/**
 *
 * @author Gihan
 */
public class Reportcomparison extends javax.swing.JFrame {

    PayRoll payroll;
    PrintSiteCompare sitecompare;
    double total1;
    double total2;
    double compamount;
    double totalamount1;
    double totalamount2;
    double totalcomp;
    
    /**
     * Creates new form Reportcomparison
     */
    public Reportcomparison() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        ycyear = new com.toedter.calendar.JYearChooser();
        jLabel16 = new javax.swing.JLabel();
        mcmonth = new com.toedter.calendar.JMonthChooser();
        bview = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ycyear1 = new com.toedter.calendar.JYearChooser();
        jLabel18 = new javax.swing.JLabel();
        mcmonth1 = new com.toedter.calendar.JMonthChooser();
        jLabel19 = new javax.swing.JLabel();
        lfmonth = new javax.swing.JLabel();
        lltotal = new javax.swing.JLabel();
        lsmonth = new javax.swing.JLabel();
        lstotal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lcompamount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsites = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Month Total Comparison");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Year");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Month");

        mcmonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        bview.setText("View");
        bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewActionPerformed(evt);
            }
        });

        bprint.setText("Print");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Year");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Month");

        mcmonth1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Total For");

        lfmonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lfmonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lfmonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lltotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lltotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lsmonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lsmonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsmonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lstotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lstotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lstotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Total For");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Change");

        lcompamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lcompamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcompamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblsites.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblsites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Site", "Total1", "Total2", "Comparison"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsites.setRowHeight(19);
        tblsites.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblsites.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(tblsites);
        tblsites.getColumnModel().getColumn(1).setMinWidth(120);
        tblsites.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblsites.getColumnModel().getColumn(1).setMaxWidth(120);
        tblsites.getColumnModel().getColumn(2).setMinWidth(120);
        tblsites.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblsites.getColumnModel().getColumn(2).setMaxWidth(120);
        tblsites.getColumnModel().getColumn(3).setMinWidth(120);
        tblsites.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblsites.getColumnModel().getColumn(3).setMaxWidth(120);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ycyear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(mcmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ycyear1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(mcmonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lsmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(lcompamount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lfmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ycyear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ycyear1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcmonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lfmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lsmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcompamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-679)/2, (screenSize.height-694)/2, 679, 694);
    }// </editor-fold>//GEN-END:initComponents

    private void bviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewActionPerformed
        loadTable2();

//        payroll = new PayRoll();
//
//        try {
//            total1 = payroll.getPayrollTotal(ycyear.getYear(), mcmonth.getMonth() + 1);
//            total2 = payroll.getPayrollTotal(ycyear1.getYear(), mcmonth1.getMonth() + 1);
//
//            if (total1 > total2) {
//                compamount = total1 - total2;
//            } else if (total2 > total1) {
//                compamount = total2 - total1;
//            } else if (total1 == total2) {
//                compamount = 0.00;
//            }
//            int m1 = mcmonth.getMonth() + 1;
//            int m2 = mcmonth1.getMonth() + 1;
//
//            lfmonth.setText("" + ycyear.getYear() + "-" + m1);
//            lsmonth.setText("" + ycyear1.getYear() + "-" + m2);
//
//            lltotal.setText(formatForDouble(total1));
//            lstotal.setText(formatForDouble(total2));
//            lcompamount.setText(formatForDouble(compamount));
//
//
//        } catch (Exception e) {
//            System.out.println("Error From UI: " + e);
//            e.printStackTrace();
//        }



    }//GEN-LAST:event_bviewActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
//        if (total1 > 0) {
//            printcomp = new Printcomparereport();
//
//            printcomp.setYear1(ycyear.getYear());
//            printcomp.setYear2(ycyear1.getYear());
//            printcomp.setMonth1(mcmonth.getMonth() + 1);
//            printcomp.setMonth2(mcmonth1.getMonth() + 1);
//            printcomp.setTotal1(total1);
//            printcomp.setTotal2(total2);
//            printcomp.setCompamount(compamount);
//
//            printcomp.printThisInvoice();
//        } else {
//            JOptionPane.showMessageDialog(null, "Get data First!", "Warning!", 2);
//        }
        
        
        if (JOptionPane.showConfirmDialog(null, "Want to Print the Table!", "Question", 0, 3) == 0) {
            sitecompare = new PrintSiteCompare();
            sitecompare.setYear(ycyear.getYear());
            sitecompare.setMonth(mcmonth.getMonth() + 1);
            sitecompare.setYear2(ycyear1.getYear());
            sitecompare.setMonth2(mcmonth1.getMonth() + 1);
            
            Vector vecsite = new Vector();
            Vector veccashamount = new Vector();
            Vector vecbankamount = new Vector();
            Vector vecamount = new Vector();
            
            for (int x = 0; x < tblsites.getRowCount(); x++) {
                vecsite.add(tblsites.getValueAt(x, 0));
                veccashamount.add(tblsites.getValueAt(x, 1));
                vecbankamount.add(tblsites.getValueAt(x, 2));
                vecamount.add(tblsites.getValueAt(x, 3));
            }
            
            sitecompare.setSitename(vecsite);
            sitecompare.setCashamount(veccashamount);
            sitecompare.setBankamount(vecbankamount);
            sitecompare.setSiteamount(vecamount);
            
            sitecompare.setCashtotalamount(totalamount1);
            sitecompare.setBanktotalamount(totalamount2);
            sitecompare.setTotalamount(totalcomp);
            
            sitecompare.printThisInvoice();
        }




   }//GEN-LAST:event_bprintActionPerformed

    void loadTable2() {
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblsites.getModel();
        total1 = 0.0;
        total2 = 0.0;
        compamount = 0.0;
        totalamount1 = 0.0;
        totalamount2 = 0.0;
        totalcomp = 0.0;
        
        try {

            ResultSet rs2 = DB.getData("SELECT * FROM site WHERE is_active = '1' AND site_ID != '26'");


            while (rs2.next()) {

                total1 = 0.0;
                total2 = 0.0;
                compamount = 0.0;

                ResultSet rs3 = Site.getSitePayAmount2(ycyear.getYear(), mcmonth.getMonth() + 1, rs2.getInt("site_ID"));
                ResultSet rs4 = Site.getSitePayAmount2(ycyear1.getYear(), mcmonth1.getMonth() + 1, rs2.getInt("site_ID"));

                while (rs3.next()) {
                    total1 += rs3.getDouble("PackSal");
//                        if(rs3.getString("PayType").equals("CASH")){
//                            cashtotal += rs3.getDouble("PackSal");
//                            System.out.println("VAL1: " + rs3.getDouble("PackSal"));
//                        }else if(rs3.getString("PayType").equals("BANK")){
//                            banktotal += rs3.getDouble("PackSal");
//                            System.out.println("VAL3: " + rs3.getDouble("PackSal"));
//                        }

                }

                while (rs4.next()) {
                    total2 += rs4.getDouble("PackSal");

                }

                if (total1 > total2) {
                    compamount = total1 - total2;
                } else if (total2 > total1) {
                    compamount = total2 - total1;
                } else if (total1 == total2) {
                    compamount = 0.0;
                }

                ArrayList vec = new ArrayList();

                vec.add(rs2.getString("site_location"));
                vec.add(total1);
                vec.add(total2);
                vec.add(compamount);
                dt.addRow(vec.toArray());
                
                totalamount1 += total1;
                totalamount2 += total2;
                
                if (totalamount1 > totalamount2) {
                    totalcomp = totalamount1 - totalamount2;
                } else if (totalamount2 > totalamount1) {
                    totalcomp = totalamount2 - totalamount1;
                } else if (totalamount1 == totalamount2) {
                    totalcomp = 0.0;
                }
                
                //totalsalamount += rs3.getDouble("finaltotal");

            }
//            totalsalamount = totalcashamount + totalbankamount;
            showValues();

        } catch (Exception e) {
            System.out.println("Error From loadTable Method: " + e);
            e.printStackTrace();
        }

    }

    void clearTable() {
        DefaultTableModel dt = (DefaultTableModel) tblsites.getModel();
        int rows = tblsites.getRowCount();
        for (int x = 0; x < rows; x++) {
            dt.removeRow(0);
        }

    }

    void showValues() {
        int m1 = mcmonth.getMonth()+1;
        int m2 = mcmonth1.getMonth()+1;
        
        lfmonth.setText(ycyear.getYear() + "-" +  m1);
        lsmonth.setText(ycyear1.getYear() + "-" +  m2);
        
        lltotal.setText(""+formatForDouble(totalamount1));
        lstotal.setText(""+formatForDouble(totalamount2));
        lcompamount.setText(""+formatForDouble(totalcomp));
    }

    public String formatForDouble(double contents) {
        String newFormNo = "";

        try {
            NumberFormat nf = NumberFormat.getNumberInstance();
            nf.setMaximumFractionDigits(2);
            nf.setMinimumFractionDigits(2);
            newFormNo = nf.format(contents);
        } catch (Exception ex) {
        }
        return newFormNo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportcomparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportcomparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportcomparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportcomparison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reportcomparison().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bprint;
    private javax.swing.JButton bview;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcompamount;
    private javax.swing.JLabel lfmonth;
    private javax.swing.JLabel lltotal;
    private javax.swing.JLabel lsmonth;
    private javax.swing.JLabel lstotal;
    private com.toedter.calendar.JMonthChooser mcmonth;
    private com.toedter.calendar.JMonthChooser mcmonth1;
    private javax.swing.JTable tblsites;
    private com.toedter.calendar.JYearChooser ycyear;
    private com.toedter.calendar.JYearChooser ycyear1;
    // End of variables declaration//GEN-END:variables
}
