/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Empsearch;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.Employeesaldata;
import model.OftnLogic;

/**
 *
 * @author Gihan
 */
public final class SalaryAssign extends javax.swing.JPanel {

    Empsearch empsearch = new Empsearch();
    Employeesaldata empsalary = new Employeesaldata();
    double basicsalary;
    double gvtallowance = 400.00;
    double budallowance = 1000.00;
    int updateid;
    int empno = 0;
    int epfno = 0;

    /**
     * Creates new form Attendance
     */
    public SalaryAssign() {
        initComponents();
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        OftnLogic.Allownaces(cmballowance);
        OftnLogic.Diductions(cmbdeduction);
        OftnLogic.additions(additions);
        showDefaultData();
        loadTable(Employeesaldata.getallSalaryinfo(-1));


    }

    public void genmethod() {

        empsearch = new Empsearch();
        tename.setText("" + listemp.getSelectedValue());
        scrollemp.setSize(scrollemp.getWidth(), 0);
        listemp.setVisible(false);
        scrollemp.setVisible(false);
        tbasicsal.grabFocus();

        this.empno = empsearch.getEmployeeNumber(tename.getText());
        lenum.setText("Emp.No: " + empno);
        lepfnum.setText("EPF. No: " + epfno);
        try {
            ResultSet rs = Employeesaldata.getallSalaryinfo(empno);
            if (rs.next()) {
                tbasicsal.setText(rs.getString("Basic_salary"));
                tgvtallowance.setText(rs.getString("gvtAllow"));
                tbudallowance.setText(rs.getString("budAllow"));
                this.epfno = rs.getInt("EmpNumber");
                updateid = this.epfno;
            } else {
                updateid = 0;
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void loadTwoother() {

        try {
            DefaultTableModel df = null;
            ResultSet rs = null;
            rs = Employee.getAllDiductions(empno);
            df = (DefaultTableModel) tbldeductions.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                ArrayList ar = new ArrayList();
                ar.add(rs.getString("emp_has_extra.extraval_id"));
                ar.add(rs.getString("Name"));
                ar.add(rs.getDouble("Value"));
                df.addRow(ar.toArray());
            }
            rs = Employee.getAllAllownace(empno);
            df = (DefaultTableModel) tblearnings.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                ArrayList ar = new ArrayList();
                ar.add("ALLOW");
                ar.add(rs.getString("Name"));
                ar.add(rs.getDouble("Value"));
            ar.add(rs.getString("emp_has_extra.extraval_id"));
                df.addRow(ar.toArray());
            }
            rs = Employee.getAdditions(empno);
            df = (DefaultTableModel) tblearnings.getModel();
            while (rs.next()) {
                ArrayList ar = new ArrayList();
                ar.add("ADD");
                ar.add(rs.getString("addition_name"));
                ar.add(rs.getDouble("Value"));
                ar.add(rs.getString("emp_has_addition.addition_id"));
                df.addRow(ar.toArray());
            }


        } catch (Exception e) {
            System.out.println("Error in add and did loading" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lepfnum = new javax.swing.JLabel();
        scrollemp = new javax.swing.JScrollPane();
        listemp = new javax.swing.JList();
        tename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbudallowance = new javax.swing.JTextField();
        tgvtallowance = new javax.swing.JTextField();
        tbasicsal = new javax.swing.JTextField();
        lenum = new javax.swing.JLabel();
        bupdate = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmballowance = new com.imal.practicalJcombSearchable.JComboPractical();
        tallowance = new javax.swing.JTextField();
        badd1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        additions = new com.imal.practicalJcombSearchable.JComboPractical();
        ldedamount = new javax.swing.JTextField();
        badd3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        cmbdeduction = new com.imal.practicalJcombSearchable.JComboPractical();
        ldedamount1 = new javax.swing.JTextField();
        badd4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsal = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblearnings = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbldeductions = new javax.swing.JTable();
        bremove4 = new javax.swing.JButton();
        bremove3 = new javax.swing.JButton();
        bremove1 = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Emp. Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 13, 65, 27));

        lepfnum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lepfnum.setForeground(new java.awt.Color(51, 51, 51));
        lepfnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lepfnum.setText("EPF. No:");
        lepfnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lepfnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, 27));

        listemp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        listemp.setForeground(new java.awt.Color(51, 51, 51));
        listemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listempMouseClicked(evt);
            }
        });
        listemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listempKeyPressed(evt);
            }
        });
        scrollemp.setViewportView(listemp);

        jPanel1.add(scrollemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 250, 30));

        tename.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tename.setForeground(new java.awt.Color(51, 51, 51));
        tename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tenameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tenameKeyReleased(evt);
            }
        });
        jPanel1.add(tename, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Basic Salary");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Gvt. Allowance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Bud. Allowance");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 27));

        tbudallowance.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbudallowance.setForeground(new java.awt.Color(51, 51, 51));
        tbudallowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbudallowanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbudallowanceKeyReleased(evt);
            }
        });
        jPanel1.add(tbudallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, 29));

        tgvtallowance.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tgvtallowance.setForeground(new java.awt.Color(51, 51, 51));
        tgvtallowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgvtallowanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tgvtallowanceKeyReleased(evt);
            }
        });
        jPanel1.add(tgvtallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 29));

        tbasicsal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbasicsal.setForeground(new java.awt.Color(51, 51, 51));
        tbasicsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbasicsalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbasicsalKeyReleased(evt);
            }
        });
        jPanel1.add(tbasicsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 29));

        lenum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lenum.setForeground(new java.awt.Color(51, 51, 51));
        lenum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lenum.setText("Emp.No:");
        lenum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 27));

        bupdate.setText("Update Data");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel1.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, 30));

        bsave.setText("Save Data");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("F.Allowances");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 27));

        cmballowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmballowanceActionPerformed(evt);
            }
        });
        jPanel1.add(cmballowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 210, 30));

        tallowance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tallowance.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(tallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 30));

        badd1.setText("Add+");
        badd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd1ActionPerformed(evt);
            }
        });
        jPanel1.add(badd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Additions");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, 27));
        jPanel1.add(additions, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, 30));

        ldedamount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ldedamount.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(ldedamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 80, 30));

        badd3.setText("Add+");
        badd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd3ActionPerformed(evt);
            }
        });
        jPanel1.add(badd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 120, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 430, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 430, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 430, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 430, 10));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel50.setText("Deductions");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 80, 27));
        jPanel1.add(cmbdeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 210, 30));

        ldedamount1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ldedamount1.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(ldedamount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 80, 30));

        badd4.setText("Add+");
        badd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badd4ActionPerformed(evt);
            }
        });
        jPanel1.add(badd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 120, 30));

        tblsal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tblsal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp.No", "Full Name", "Basic", "Gvt.All.", "Bud.All."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblsal.setRowHeight(21);
        tblsal.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblsal.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblsal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsal);
        tblsal.getColumnModel().getColumn(0).setMinWidth(60);
        tblsal.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblsal.getColumnModel().getColumn(0).setMaxWidth(60);
        tblsal.getColumnModel().getColumn(2).setMinWidth(60);
        tblsal.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblsal.getColumnModel().getColumn(2).setMaxWidth(60);
        tblsal.getColumnModel().getColumn(3).setMinWidth(60);
        tblsal.getColumnModel().getColumn(3).setPreferredWidth(60);
        tblsal.getColumnModel().getColumn(3).setMaxWidth(60);
        tblsal.getColumnModel().getColumn(4).setMinWidth(60);
        tblsal.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblsal.getColumnModel().getColumn(4).setMaxWidth(60);

        jPanel4.setBackground(new java.awt.Color(128, 128, 128));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgtop_attendance.jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tblearnings.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tblearnings.setForeground(new java.awt.Color(0, 102, 255));
        tblearnings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Allowance / Additions", "Price", "AlowID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblearnings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblearnings.setRowHeight(21);
        tblearnings.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tblearnings.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane3.setViewportView(tblearnings);
        tblearnings.getColumnModel().getColumn(0).setMinWidth(62);
        tblearnings.getColumnModel().getColumn(0).setPreferredWidth(62);
        tblearnings.getColumnModel().getColumn(0).setMaxWidth(62);
        tblearnings.getColumnModel().getColumn(2).setMinWidth(60);
        tblearnings.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblearnings.getColumnModel().getColumn(2).setMaxWidth(60);
        tblearnings.getColumnModel().getColumn(3).setMinWidth(0);
        tblearnings.getColumnModel().getColumn(3).setPreferredWidth(0);
        tblearnings.getColumnModel().getColumn(3).setMaxWidth(0);

        tbldeductions.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbldeductions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Deductions", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldeductions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldeductions.setRowHeight(21);
        tbldeductions.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tbldeductions.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane4.setViewportView(tbldeductions);
        tbldeductions.getColumnModel().getColumn(0).setMinWidth(50);
        tbldeductions.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbldeductions.getColumnModel().getColumn(0).setMaxWidth(50);
        tbldeductions.getColumnModel().getColumn(2).setMinWidth(60);
        tbldeductions.getColumnModel().getColumn(2).setPreferredWidth(60);
        tbldeductions.getColumnModel().getColumn(2).setMaxWidth(60);

        bremove4.setText("Remove Did");
        bremove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove4ActionPerformed(evt);
            }
        });

        bremove3.setText("Remove Additions");
        bremove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove3ActionPerformed(evt);
            }
        });

        bremove1.setText("Remove Allowance");
        bremove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremove1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bremove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bremove3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bremove4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1167, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bremove4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bremove3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bremove1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(285, 285, 285)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenameKeyReleased
        empsearch = new Empsearch();
        empsearch.employeeSearch(listemp, scrollemp, tename.getText());

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listemp.grabFocus();

        }

    }//GEN-LAST:event_tenameKeyReleased

    private void tenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            listemp.grabFocus();

        }
    }//GEN-LAST:event_tenameKeyPressed

    private void listempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listempKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            genmethod();
        }
    }//GEN-LAST:event_listempKeyPressed

    private void listempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listempMouseClicked
        genmethod();

    }//GEN-LAST:event_listempMouseClicked

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        if (formCheck()) {
            empsalary.setEmpno(empno);
            empsalary.setBasic(basicsalary);
            empsalary.setGvtall(gvtallowance);
            empsalary.setBudall(budallowance);
            if (empsalary.assignSalaryData()) {
                JOptionPane.showMessageDialog(null, "Successfully Assign Salary Data!", "Done!", 1);
                loadTable(Employeesaldata.getallSalaryinfo(-1));
            } else {
                JOptionPane.showMessageDialog(null, "Error While Assigning Salary Data!", "Warning!", 0);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Employee & His/Her Full Days Essential!", "Warning!", 2);
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void tbasicsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbasicsalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tgvtallowance.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tename.grabFocus();
        }
    }//GEN-LAST:event_tbasicsalKeyPressed

    private void tgvtallowanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgvtallowanceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tbudallowance.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tbasicsal.grabFocus();
        }
    }//GEN-LAST:event_tgvtallowanceKeyPressed

    private void tbudallowanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbudallowanceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tbasicsal.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tgvtallowance.grabFocus();
        }
    }//GEN-LAST:event_tbudallowanceKeyPressed

    private void tbasicsalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbasicsalKeyReleased
        this.basicsalary = Double.parseDouble(tbasicsal.getText());

    }//GEN-LAST:event_tbasicsalKeyReleased

    private void tgvtallowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgvtallowanceKeyReleased
        this.gvtallowance = Double.parseDouble(tgvtallowance.getText());
    }//GEN-LAST:event_tgvtallowanceKeyReleased

    private void tbudallowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbudallowanceKeyReleased
        this.budallowance = Double.parseDouble(tbudallowance.getText());
    }//GEN-LAST:event_tbudallowanceKeyReleased

    private void tblsalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsalMouseClicked
        bsave.setEnabled(false);
        bupdate.setEnabled(true);

        try {
            updateid = Integer.parseInt(tblsal.getValueAt(tblsal.getSelectedRow(), 0).toString());
            empno = updateid;
            
            this.basicsalary = Double.parseDouble(tblsal.getValueAt(tblsal.getSelectedRow(), 2).toString());
            this.gvtallowance = Double.parseDouble(tblsal.getValueAt(tblsal.getSelectedRow(), 3).toString());
            this.budallowance = Double.parseDouble(tblsal.getValueAt(tblsal.getSelectedRow(), 4).toString());
            
            tename.setText(tblsal.getValueAt(tblsal.getSelectedRow(), 1).toString());
            tbasicsal.setText(""+basicsalary);
            tgvtallowance.setText(""+gvtallowance);
            tbudallowance.setText(""+budallowance);

            loadTwoother();

        } catch (Exception e) {
            System.out.println("No Record Selected! " + e);
        }

    }//GEN-LAST:event_tblsalMouseClicked

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        if (updateid != 0) {
            if (formCheck()) {
                empsalary.setBasic(basicsalary);
                empsalary.setGvtall(gvtallowance);
                empsalary.setBudall(budallowance);

                System.out.println(basicsalary + " " + gvtallowance + " " + budallowance);
                if (empsalary.updateSalaryData(updateid)) {
                    JOptionPane.showMessageDialog(null, "Successfully Updated Salary Data!", "Done!", 1);
                    loadTable(Employeesaldata.getallSalaryinfo(-1));
                } else {
                    JOptionPane.showMessageDialog(null, "Error While Updating Salary Data!", "Warning!", 0);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Employee & His/Her Full Days Essential!", "Warning!", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select Employee From Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void cmballowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmballowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmballowanceActionPerformed

    private void badd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd1ActionPerformed
        if (tblsal.getSelectedRow() != -1 && !tallowance.getText().trim().isEmpty()) {
            Employee.AddAllowDID(cmballowance.getSelectedDataItemID(), updateid, tallowance.getText());
            loadTwoother();
        }
    }//GEN-LAST:event_badd1ActionPerformed

    private void bremove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove1ActionPerformed
        if (tblearnings.getSelectedRow() != -1) {
            if (tblearnings.getValueAt(tblearnings.getSelectedRow(), 0).toString().equals("ALLOW")) {
                Employee.deleteAllowAdd(Integer.parseInt(tblearnings.getValueAt(tblearnings.getSelectedRow(), 3).toString()), updateid);
                loadTwoother();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Row in Allowance /Addition table", "SELECT TABLE ROW", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bremove1ActionPerformed

    private void badd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd3ActionPerformed
        if (tblsal.getSelectedRow() != -1 && !ldedamount.getText().trim().isEmpty()) {
            Employee.AddAaddition(additions.getSelectedDataItemID(), updateid, ldedamount.getText());
            loadTwoother();
        }
    }//GEN-LAST:event_badd3ActionPerformed

    private void bremove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove3ActionPerformed
        if (tblearnings.getSelectedRow() != -1) {
            if (tblearnings.getValueAt(tblearnings.getSelectedRow(), 0).toString().equals("ADD")) {
                Employee.deleteAddition(Integer.parseInt(tblearnings.getValueAt(tblearnings.getSelectedRow(), 3).toString()), updateid);
                loadTwoother();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Row in Allowance /Addition table", "SELECT TABLE ROW", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bremove3ActionPerformed

    private void badd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badd4ActionPerformed
        if (tblsal.getSelectedRow() != -1 && !ldedamount1.getText().trim().isEmpty()) {
            Employee.AddAllowDID(cmbdeduction.getSelectedDataItemID(), updateid, ldedamount1.getText());
            loadTwoother();
        }
    }//GEN-LAST:event_badd4ActionPerformed

    private void bremove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremove4ActionPerformed
        if (tbldeductions.getSelectedRow() != -1) {
            Employee.deleteAllowAdd(Integer.parseInt(tbldeductions.getValueAt(tbldeductions.getSelectedRow(), 0).toString()), updateid);
            loadTwoother();
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Row in diduction table", "SELECT TABLE ROW", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bremove4ActionPerformed

    boolean formCheck() {
        boolean val = false;

        try {
            if (tename.getText().trim().equals("") || empno == 0 || tbasicsal.getText().trim().equals("") || tgvtallowance.getText().trim().equals("") || tbudallowance.getText().trim().equals("")) {
                val = false;
            } else {
                val = true;
            }
        } catch (Exception e) {
            val = false;
        }

        return val;
    }

    void loadTable(ResultSet rs) {
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblsal.getModel();

        try {
            while (rs.next()) {
                ArrayList vec = new ArrayList<>();
                vec.add(rs.getInt("EmpNumber"));
                vec.add(rs.getString("FMname") + " " + rs.getString("Lname"));
                vec.add(rs.getDouble("Basic_salary"));
                vec.add(rs.getDouble("gvtAllow"));
                vec.add(rs.getDouble("budAllow"));
                dt.addRow(vec.toArray());
            }

        } catch (Exception e) {
            System.out.println("Error From loadTable Method: " + e);
        }

    }

    void clearTable() {
        DefaultTableModel dt = (DefaultTableModel) tblsal.getModel();
        int rows = tblsal.getRowCount();
        for (int x = 0; x < rows; x++) {
            dt.removeRow(0);
        }

    }

    void showDefaultData() {
        tgvtallowance.setText("" + this.gvtallowance);
        tbudallowance.setText("" + this.budallowance);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.imal.practicalJcombSearchable.JComboPractical additions;
    private javax.swing.JButton badd1;
    private javax.swing.JButton badd3;
    private javax.swing.JButton badd4;
    private javax.swing.JButton bremove1;
    private javax.swing.JButton bremove3;
    private javax.swing.JButton bremove4;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bupdate;
    private com.imal.practicalJcombSearchable.JComboPractical cmballowance;
    private com.imal.practicalJcombSearchable.JComboPractical cmbdeduction;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField ldedamount;
    private javax.swing.JTextField ldedamount1;
    private javax.swing.JLabel lenum;
    private javax.swing.JLabel lepfnum;
    private javax.swing.JList listemp;
    private javax.swing.JScrollPane scrollemp;
    private javax.swing.JTextField tallowance;
    private javax.swing.JTextField tbasicsal;
    private javax.swing.JTable tbldeductions;
    private javax.swing.JTable tblearnings;
    private javax.swing.JTable tblsal;
    private javax.swing.JTextField tbudallowance;
    private javax.swing.JTextField tename;
    private javax.swing.JTextField tgvtallowance;
    // End of variables declaration//GEN-END:variables
}
